---
# calculate worktimes
alias: calculateWorkTimes
id: fbb333c2-757c-414a-8d34-5fe6fc995029
description: "Calculate worktimes"
trigger:
  - trigger: time
    at: "23:59:00"
    id: daily_update
condition: []
action:
  - variables:
      pause_hours: "{{ states('number.miguel_calc_pause') | float(0) }}"
      daily_worked: "{{ states('sensor.miguel_arbeit_daily') | float(0) }}"
      weekly_target: "{{ states('input_number.wochenarbeitszeit_miguel') | float(0) }}"
      weekly_hours_so_far: "{{ states('input_number.miguel_arbeit_woche') | float(0) }}"
      daily_target_hours: "{{ (weekly_target / 5) | round(2) }}"
      is_workday: "{{ is_state('binary_sensor.workday_sensor', 'on') }}"
      is_mon_fri: "{{ now().weekday() < 5 }}"
      is_holiday: "{{ is_mon_fri and not is_workday }}"
      actual_net: "{{ ([0, (daily_worked - pause_hours)] | max) | round(2) }}"
      hours_to_add: >
        {% if is_workday and daily_worked == 0 %}
          {{ daily_target_hours }}
        {% elif is_holiday %}
          {{ (daily_target_hours + actual_net) | round(2) }}
        {% else %}
          {{ actual_net }}
        {% endif %}
  - action: input_number.set_value
    target:
      entity_id: input_number.miguel_arbeit_woche
    data:
      value: "{{ (weekly_hours_so_far + hours_to_add) | round(2) }}"
  - if:
      - condition: template
        value_template: "{{ now().weekday() == 6 }}"
    then:
      - variables:
          updated_weekly: "{{ (weekly_hours_so_far + hours_to_add) | round(2) }}"
          weekly_difference: "{{ (updated_weekly - weekly_target) | round(2) }}"
          current_stundenkonto: "{{ states('input_number.miguel_arbeit_stundenkonto') | float(0) }}"
      - action: input_number.set_value
        target:
          entity_id: input_number.miguel_arbeit_stundenkonto
        data:
          value: "{{ (current_stundenkonto + weekly_difference) | round(2) }}"
      - action: input_number.set_value
        target:
          entity_id: input_number.miguel_arbeit_woche
        data:
          value: 0
mode: single
