---
# Get work restaurant html page
alias: getWorkRestHTML
id: 91949311-550e-466b-abf0-996d26e324f9
description: "Get work restaurant html page"
trigger:
  - trigger: time
    at: "20:00:00"
condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: "on"
action:
  - action: shell_command.browserless_scraper
    data:
      function: "work_restaurant.js"
      output: "work_restaurant.html"
  - delay: "0:00:45"
  - action: multiscrape.trigger_work_meals
mode: single
