---
# notify about the meals
alias: workMeals
id: a601d3fe-17d3-4cff-9eb1-ea4bbca2c549
description: "Notify about the work meals"
trigger:
  - trigger: time
    at: "11:00:00"
condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: "on"
  - condition: state
    entity_id: schedule.buro_tage
    state: "on"
  - condition: not
    conditions:
      - condition: state
        entity_id: person.miguel
        state: "home"
action:
  - action: script.notify_engine
    data:
      title: |
        🍴 Heutiges Essen im Geschäft 🍽️
      value1: |
        Heute im Geschäft gibt es folgende Gerichte:
      who: "home"
      tag_id: "information"
      group: "Work"
      photo:
        path: "/config/www/downloaded/work_meals/one.png"
        caption: "{{ states('input_text.work_meal_one') }}"
  - action: script.notify_engine
    data:
      title: |
        🍴 Heutiges Essen im Geschäft 🍽️
      value1: |
        Heute im Geschäft gibt es folgende Gerichte:
      who: "home"
      tag_id: "information"
      group: "Work"
      photo:
        path: "/config/www/downloaded/work_meals/one_two.png"
        caption: "{{ states('input_text.work_meal_one_two') }}"
  - action: script.notify_engine
    data:
      title: |
        🍴 Heutiges Essen im Geschäft 🍽️
      value1: |
        Heute im Geschäft gibt es folgende Gerichte:
      who: "home"
      tag_id: "information"
      group: "Work"
      photo:
        path: "/config/www/downloaded/work_meals/three.png"
        caption: "{{ states('input_text.work_meal_three') }}"
  - action: script.notify_engine
    data:
      title: |
        🍴 Heutiges Essen im Geschäft 🍽️
      value1: |
        Heute im Geschäft gibt es folgende Gerichte:
      who: "home"
      tag_id: "information"
      group: "Work"
      photo:
        path: "/config/www/downloaded/work_meals/four.png"
        caption: "{{ states('input_text.work_meal_four') }}"
  - action: script.notify_engine
    data:
      title: |
        🍴 Heutiges Essen im Geschäft 🍽️
      value1: |
        Heute im Geschäft gibt es folgende Gerichte:
      who: "home"
      tag_id: "information"
      group: "Work"
      photo:
        path: "/config/www/downloaded/work_meals/five.png"
        caption: "{{ states('input_text.work_meal_five') }}"
mode: single
