---
# notify about the meals
alias: workMeals
id: a601d3fe-17d3-4cff-9eb1-ea4bbca2c549
description: "Notify about the work meals"
trigger:
  - trigger: time
    at: "11:15:00"
    alias: "Trigger at 11:00 AM"
condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: "on"
    alias: "Check if it is a workday"
  - condition: state
    entity_id: schedule.buro_tage
    state: "on"
    alias: "Check if office schedule is active"
  - condition: not
    conditions:
      - condition: state
        entity_id: person.miguel
        state: "home"
    alias: "Ensure Miguel is not at home"
action:
  - alias: "Iterate through all work meal items"
    repeat:
      for_each:
        - "one"
        - "one_two"
        - "three"
        - "four"
        - "five"
        - "six"
      sequence:
        - action: script.notify_engine
          alias: "Send notification for current meal"
          data:
            title: |
              🍴 Heutiges Essen im Geschäft 🍽️
            value1: |
              Heute im Geschäft gibt es folgende Gerichte:
            who: "home"
            tag_id: "information"
            group: "Work"
            photo:
              path: "{{ states('input_text.local_url') }}{{ state_attr('image.work_meal_' ~ repeat.item, 'entity_picture') }}"
              caption: "{{ states('input_text.work_meal_' ~ repeat.item) }}"
  - action: notify.kohgeb_family_home
    data:
      title: Speiseplan
      message: Heutiger Speiseplan
      data:
        images:
          - /config/www/downloaded/work_meals/work_meal_one.png
          - /config/www/downloaded/work_meals/work_meal_one_two.png
          - /config/www/downloaded/work_meals/work_meal_three.png
          - /config/www/downloaded/work_meals/work_meal_four.png
          - /config/www/downloaded/work_meals/work_meal_five.png
          - /config/www/downloaded/work_meals/work_meal_six.png
      target:
        - "{{ states('input_text.miguel_work_mail') }}"
mode: single
