---
# notify about the meals
alias: workMeals
id: a601d3fe-17d3-4cff-9eb1-ea4bbca2c549
description: "Notify about the work meals"
trigger:
  - trigger: time
    at: "11:00:00"
    alias: "Trigger at 11:00 AM"
condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: "on"
    alias: "Check if it is a workday"
  - condition: state
    entity_id: schedule.buro_tage
    state: "on"
    alias: "Check if office schedule is active"
  - condition: not
    conditions:
      - condition: state
        entity_id: person.miguel
        state: "home"
    alias: "Ensure Miguel is not at home"
action:
  - alias: "Iterate through all work meal items"
    repeat:
      for_each:
        - "one"
        - "one_two"
        - "three"
        - "four"
        - "five"
      sequence:
        - action: script.notify_engine
          alias: "Send notification for current meal"
          data:
            title: |
              🍴 Heutiges Essen im Geschäft 🍽️
            value1: |
              Heute im Geschäft gibt es folgende Gerichte:
            who: "home"
            tag_id: "information"
            group: "Work"
            photo:
              path: "/config/www/downloaded/work_meals/{{ repeat.item }}.png"
              caption: "{{ states('input_text.work_meal_' ~ repeat.item) }}"
mode: single
