---
# Milo Kita
alias: MiloKita
id: b2aeeef6-6e1f-441d-a1b4-1b678cd97467
description: "Status aktualisieren, wenn Milo in der Kita ist."
trigger:
  - platform: state
    entity_id: schedule.milo_kita_zeiten
condition: []
action:
  - if:
      - condition: state
        entity_id: schedule.milo_kita_zeiten
        state: "on"
    then:
      - action: input_select.select_option
        target:
          entity_id: input_select.milo_person_sync
        data:
          option: alleine
      - service: device_tracker.see
        data:
          location_name: "Kita"
          dev_id: milo_dummy_tracker
    else:
      - action: input_select.select_option
        target:
          entity_id: input_select.milo_person_sync
        data:
          option: silke
mode: single
