---
# Milo Kita
alias: MiloKita
id: b2aeeef6-6e1f-441d-a1b4-1b678cd97467
description: "Status aktualisieren, wenn Milo in der Kita ist."
trigger:
  - platform: state
    entity_id: schedule.milo_kita_zeiten
condition:
  - condition: state
    entity_id: binary_sensor.milo_kita
    state: "on"
action:
  - if:
      - condition: state
        entity_id: schedule.milo_kita_zeiten
        state: "on"
    then:
      - action: script.change_dummy_locations
        data:
          who: milo
          target_zone: zone.kita
    else:
      - action: input_select.select_option
        target:
          entity_id: input_select.milo_person_sync
        data:
          option: silke
mode: single
