---
# Automation when work laptop goes online
alias: workStarting
id: bece8ed6-e1d0-44d9-a167-85413735c362
description: Geschäftslaptop befindet sich im Netz
trigger:
  - platform: state
    entity_id: device_tracker.bcwmc002867
    to: home
condition:
  - condition: state
    entity_id: input_boolean.status_light
    state: "on"
action:
  - service: scene.create
    data:
      snapshot_entities:
        - light.schreibtischlicht
      scene_id: pre_work
  - service: light.turn_on
    data:
      color_name: darkgreen
    target:
      entity_id: light.schreibtischlicht
  - service: light.turn_on
    data:
      effect: blink
    target:
      entity_id: light.schreibtischlicht
  - service: scene.turn_on
    target:
      entity_id: scene.pre_work
    data: {}
mode: single
