---
# work meal ai img
alias: WorkMealImg
description: ""
id: ffe67e29-366b-4661-a0b0-bfea95d4468e
triggers:
  - trigger: state
    entity_id: sensor.work_meal_one
    id: one
  - trigger: state
    entity_id: sensor.work_meal_one_two
    id: one_two
  - trigger: state
    entity_id: sensor.work_meal_three
    id: three
  - trigger: state
    entity_id: sensor.work_meal_four
    id: four
  - trigger: state
    entity_id: sensor.work_meal_five
    id: five
conditions:
  - condition: template
    value_template: "{{  states(trigger.entity_id) != 'unavailable' }}"
actions:
  - action: openai_conversation.generate_image
    data:
      size: 1024x1024
      quality: standard
      style: vivid
      config_entry: 01JAE4ZR2CG7T0XTAV08YDB7SS
      prompt: >-
        Generiere ein realistisches Bild von folgendem Essen:
        {{ states(trigger.entity_id) }}
        Der Fokus sollte auf dem Essen sein.
    response_variable: meal
  - action: downloader.download_file
    data:
      overwrite: true
      url: "{{ meal.url }}"
      filename: "{{ trigger.id }}.png"
      subdir: work_meals
mode: parallel
