---
# Calculate ev prices
id: 93113720-b24b-4681-a767-0d7e06f62cae
alias: calcEVPrices
description: Elektroauto preise berechnen
trigger:
  - platform: state
    entity_id: sensor.fordpass_tourneo_energytransferlogentry
condition: []
action:
  - variables:
      entity: "{{ trigger.entity_id }}"
      charger_network: "{{ state_attr(entity, 'location')['network'] | default('', true) | lower }}"
      charging_lat: "{{ state_attr(entity, 'location')['latitude'] }}"
      charging_lon: "{{ state_attr(entity, 'location')['longitude'] }}"

      # Zone ermitteln
      charging_zone: >
        {% set ns = namespace(active='not_home') %}
        {% if charging_lat != None and charging_lon != None %}
          {% for z in states.zone %}
            {% set dist = distance(charging_lat, charging_lon, z.entity_id) %}
            {% set radius_km = state_attr(z.entity_id, 'radius') | float(0) / 1000 %}
            {% if dist is not none and dist <= radius_km %}
              {% set ns.active = z.entity_id %}
            {% endif %}
          {% endfor %}
        {% endif %}
        {{ ns.active }}

      # Rohdaten (in Sekunden und kWh)
      energy_consumed: "{{ state_attr(entity, 'energyConsumed') | float(0) }}"
      plugged_in_time_sec: "{{ state_attr(entity, 'plugDetails')['totalPluggedInTime'] | float(0) }}"
      energy_transmission_time_sec: "{{ state_attr(entity, 'energyTransferDuration')['totalTime'] | float(0) }}"

      # --- TARIF-LOGIK ---
      kw_price: >
        {% if charging_zone == 'zone.work_miguel' %} 0.30
        {% elif charger_network == 'smatrics' or charger_network == 'stadtwerke heilbronn' %} 0.65
        {% elif charger_network == 'bosch' %} 0.50
        {% elif charger_network == 'enbw' %} 0.70
        {% elif charger_network == 'eze network' %} 0.39
        {% else %} 0.0 {% endif %}

      block_free_time_sec: >
        {% if charging_zone == 'zone.work_miguel' %} {{ 240 * 60 }}
        {% else %} 0 {% endif %}

      blocking_price_per_min: >
        {% if charging_zone == 'zone.work_miguel' %} 0.10
        {% elif charger_network == 'eze network' %} 0.03
        {% else %} 0.0 {% endif %}

      idle_price_per_min: >
        {% if charger_network in ['smatrics', 'enbw'] %} 0.12
        {% else %} 0.0 {% endif %}

  - variables:
      # --- ZEIT-BERECHNUNG (in Minuten) ---
      blocking_time_min: "{{ ([plugged_in_time_sec - block_free_time_sec, 0] | max / 60) | float }}"
      idle_time_min: "{{ ([plugged_in_time_sec - energy_transmission_time_sec, 0] | max / 60) | float }}"

      # --- PREIS-BERECHNUNG ---
      charging_total: "{{ (kw_price | float(0) * energy_consumed) | round(2) }}"
      blocking_total: "{{ (blocking_time_min * blocking_price_per_min | float(0)) | round(2) }}"
      idle_total: "{{ (idle_time_min * idle_price_per_min | float(0)) | round(2) }}"

      total_price: "{{ (charging_total + blocking_total + idle_total) | round(2) }}"

  - action: input_number.set_value
    target:
      entity_id: input_number.last_ev_charging_price
    data:
      value: "{{ total_price }}"
