---
# Refresh car data
alias: "Check FordPass Last Refresh"
id: af2a6157-b2f2-4b20-94cc-d2c6b8bc48f5
mode: restart

trigger:
  - platform: time_pattern
    seconds: "/15"
    id: "trigger_periodic"
    alias: "Periodic background check every 15 seconds"

  - platform: state
    entity_id:
      - binary_sensor.pixel_9_pro_android_auto
      - binary_sensor.silke_handy_android_auto
    to: "on"
    id: "trigger_car_active"
    alias: "Immediate trigger when Android Auto connects"

  - platform: state
    entity_id: group.parents
    from: "2"
    id: "trigger_parent_left"
    alias: "Immediate trigger when a parent leaves"

condition: []

action:
  - alias: "Define calculation variables"
    variables:
      time_since_refresh: >
        {% set dt = states('sensor.fordpass_tourneo_lastrefresh') | as_datetime %}
        {% set last = dt if dt != None else (now() - timedelta(days=1)) %}
        {{ (now() - last).total_seconds() }}
      is_driving: "{{ is_state('binary_sensor.pixel_9_pro_android_auto', 'on') or is_state('binary_sensor.silke_handy_android_auto', 'on') }}"
      is_away: "{{ not is_state('device_tracker.fordpass_tourneo', 'home') }}"
      interval_active: 15
      interval_idle: 900

  - alias: "Determine update strategy based on conditions"
    choose:
      - alias: "Force immediate update because an event happened right now"
        conditions:
          - condition: trigger
            id:
              - "trigger_car_active"
              - "trigger_parent_left"
            alias: "Triggered by Android Auto or Parents Group"
        sequence:
          - action: button.press
            target:
              entity_id: button.fordpass_tourneo_request_refresh
            alias: "Request FordPass Refresh (Immediate)"

      - alias: "Active interval update (Car is away or driving)"
        conditions:
          - condition: template
            value_template: "{{ is_driving or is_away }}"
            alias: "Check if driving or away"
          - condition: template
            value_template: "{{ time_since_refresh | float >= interval_active }}"
            alias: "Check if active interval is reached"
        sequence:
          - action: button.press
            target:
              entity_id: button.fordpass_tourneo_request_refresh
            alias: "Request FordPass Refresh (Active)"

      - alias: "Idle interval update (Car is home and not driving)"
        conditions:
          - condition: template
            value_template: "{{ not is_driving and not is_away }}"
            alias: "Check if not driving and not away"
          - condition: template
            value_template: "{{ time_since_refresh | float >= interval_idle }}"
            alias: "Check if idle interval is reached"
        sequence:
          - action: button.press
            target:
              entity_id: button.fordpass_tourneo_request_refresh
            alias: "Request FordPass Refresh (Idle)"
