---
# Refresh car data
alias: "Check FordPass Last Refresh"
id: af2a6157-b2f2-4b20-94cc-d2c6b8bc48f5
mode: single
trigger:
  - platform: time_pattern
    minutes: "/1"
condition:
  - condition: template
    value_template: >
      {% set refresh_time = states('sensor.fordpass_tourneo_lastrefresh') | as_datetime %}
      {{ refresh_time != None and (now() - refresh_time) > timedelta(minutes=1) }}

action:
  - action: button.press
    target:
      entity_id: button.fordpass_tourneo_request_refresh
