---
alias: FoodReadyNotif
id: 58d4291a-9465-4620-934d-bbc5ca94f7bc
description: "Benachrichtigt wenn das Essen fertig ist."
trigger: []
condition: []
action:
  - variables:
      message: "Essen ist fertig."
  - action: script.notify_engine
    data:
      title: |
        👨‍🍳 Essen 👨‍🍳
      value1: "{{ message }}"
      who: "home, home_audio"
      tag_id: "information"
      group: "Food"

mode: queued
