---
alias: FoodReadyNotif
id: 58d4291a-9465-4620-934d-bbc5ca94f7bc
description: "Benachrichtigt wenn das Essen fertig ist."
trigger:
  - domain: mqtt
    device_id: ee1b9de2827cfce71d276bf85218e92f
    type: action
    subtype: "on"
    metadata: {}
    trigger: device
condition: []
action:
  - variables:
      message: "Essen ist fertig."
  - if:
      - condition: state
        entity_id: input_boolean.audible_notifications
        state: "on"
        alias: "Check 4 audible notifications"
    then:
      - action: notify.send_message
        target:
          entity_id: notify.wohnung_durchsagen
        data:
          message: "{{ message }}"
    else:
      - if:
          - condition: state
            entity_id: input_boolean.text_notifications
            state: "on"
        then:
          - action: script.notify_engine
            data:
              title: |
                👨‍🍳 Essen 👨‍🍳
              value1: "{{ message }}"
              who: "home"
              tag_id: "information"
              group: "Food"

mode: parallel
