---
id: 6fd45ed2-56fb-4ce7-a2af-10f43953c8a5
alias: Nachtlicht starten
description: ""
triggers:
  - trigger: state
    entity_id:
      - binary_sensor.schlafzimmerbewegungssensor_occupancy
    to:
      - "on"
    enabled: false
  - trigger: state
    entity_id:
      - light.kinderzimmer
    to:
      - "off"
    from:
      - "on"
conditions:
  - condition: state
    state:
      - "on"
    entity_id: binary_sensor.bett_tracker
  - condition: time
    after: "21:00:00"
    before: 08:00:00
actions:
  - action: timer.start
    metadata: {}
    data: {}
    target:
      entity_id: timer.nachtlicht
mode: single
