---
id: 6fd45ed2-56fb-4ce7-a2af-10f43953c8a5
alias: Nachtlicht starten
description: ""
triggers:
  - trigger: state
    entity_id:
      - binary_sensor.schlafzimmerbewegungssensor_bewegung
    to:
      - "on"
    enabled: false
  - type: occupied
    device_id: a257deff16350470fa598c15e07d43d3
    entity_id: 2e02366a69abbde5c61a1c9005c92824
    domain: binary_sensor
    trigger: device
  - trigger: state
    entity_id:
      - light.kinderzimmer
    to:
      - "off"
    from:
      - "on"
conditions:
  - condition: state
    entity_id: input_boolean.automatic_lights
    state: "on"
  - condition: state
    state: "on"
    entity_id: binary_sensor.bett_tracker
  - condition: time
    after: "21:00:00"
    before: 08:00:00
actions:
  - action: timer.start
    metadata: {}
    data: {}
    target:
      entity_id: timer.nachtlicht
mode: single
