---
# Update documentation
alias: UpdateDocumentation
id: 6b1b4b5e-8da3-48a1-904f-a20728b3c67c
description: "Automatischer commit und update der Docu"
trigger:
  - trigger: time
    at: "23:55:00"
condition: []
action:
  - service: script.update_docs_script
  - service: shell_command.update_docs
mode: single
