---
# Call monitor
var:
  callmon_name:
    restore: true
    icon: mdi:phone-classic
    friendly_name: "Anrufername"
    value_template: "{{ states.sensor.fritz_box_7590_ax_anrufmonitor_telefonbuch.attributes.from_name }}"
  callmon_number:
    restore: true
    icon: mdi:card-account-phone
    friendly_name: "Anrufernummer"
    value_template: "{{ states.sensor.fritz_box_7590_ax_anrufmonitor_telefonbuch.attributes.from }}"
  callmon_time:
    restore: true
    icon: mdi:clock-time-three-outline
    friendly_name: "Anrufzeit"
    value_template: '{{ now().strftime("%H:%M") }}'
  callmon_date:
    restore: true
    icon: mdi:calendar-today
    friendly_name: "Anrufdatum"
    value_template: '{{ now().strftime("%d.%m.%Y") }}'

sensor:
  - platform: template
    sensors:
      phone_line_status:
        friendly_name: "Telefon Status"
        value_template: >-
          {% if is_state("sensor.fritz_box_7590_ax_anrufmonitor_telefonbuch", "idle") %}
              Idle
          {% elif is_state("sensor.fritz_box_7590_ax_anrufmonitor_telefonbuch", "dialing") %}
              {{ states.sensor.fritz_box_7590_ax_anrufmonitor_telefonbuch.attributes.to_name }} ({{ states.sensor.fritz_box_7590_ax_anrufmonitor_telefonbuch.attributes.to }})
          {% elif is_state("sensor.fritz_box_7590_ax_anrufmonitor_telefonbuch", "ringing") %}
              {{ states.sensor.fritz_box_7590_ax_anrufmonitor_telefonbuch.attributes.from_name }} ({{ states.sensor.fritz_box_7590_ax_anrufmonitor_telefonbuch.attributes.from }})
          {% else %}
              {{ states.sensor.fritz_box_7590_ax_anrufmonitor_telefonbuch.attributes.with_name }} ({{ states.sensor.fritz_box_7590_ax_anrufmonitor_telefonbuch.attributes.with }})
          {% endif %}
        icon_template: >-
          {% if is_state("sensor.fritz_box_7590_ax_anrufmonitor_telefonbuch", "idle") %}
              mdi:phone-classic
          {% elif is_state("sensor.fritz_box_7590_ax_anrufmonitor_telefonbuch", "dialing") %}
              mdi:phone-outgoing
          {% elif is_state("sensor.fritz_box_7590_ax_anrufmonitor_telefonbuch", "ringing") %}
              mdi:phone-incoming
          {% else %}
              mdi:phone-in-talk
          {% endif %}
