---
# Sets up Home Assistant.
#
# Basically, everything that doesn't have to be in the
# main configuration.yaml.
#
homeassistant:
  time_zone: Europe/Berlin
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: !secret home_elevation
  # Lets me customize individual entities
  customize: !include_dir_named ../customizations/entities
  media_dirs:
    haunted_sounds: /media/haunted_sounds
    music: /media/music
  allowlist_external_dirs:
    - /config/www
    - /media
