---
# meteo alarm
# https://www.home-assistant.io/integrations/meteoalarm/
binary_sensor:
  - platform: meteoalarm
    country: "spain"
    province: !secret meteoalarm_province
    language: "es-ES"
