---
# Rain statistics
sensor:
  - platform: history_stats
    name: Rained last day
    entity_id: input_boolean.raining
    state: "on"
    type: time
    end: "{{ now().replace(hour=0, minute=0, second=0) }}"
    duration:
      hours: 24
