---
binary_sensor:
  - platform: tod
    name: Morgen
    after: sunrise
    after_offset: "-02:00"
    before: "10:00"
  - platform: tod
    name: Vormittag
    after: "10:00"
    before: "12:00"
  - platform: tod
    name: Mittag
    after: "12:00"
    before: "14:00"
  - platform: tod
    name: Nachmittag
    after: "14:00"
    before: "18:00"
  - platform: tod
    name: Abend
    after: "18:00"
    before: sunset
  - platform: tod
    name: Nacht
    after: sunset
    before: sunrise

sensor:
  - platform: template
    sensors:
      day_of_week:
        value_template: "{{ now().isoweekday() }}"
        icon_template: mdi:calendar-today
      weekday:
        value_template: "{{ now().strftime('%A') }}"
        icon_template: mdi:calendar-today
  - platform: time_date
    display_options:
      - "time"
      - "date_time_iso"
      - "date"
