- id: '1690789658458'
  alias: Android Auto Miguel
  description: ''
  trigger:
  - trigger: state
    entity_id:
    - binary_sensor.pixel_9_pro_android_auto
    to: 'on'
  condition: []
  action:
  - action: notify.mobile_app_pixel_9_pro
    data:
      title: Connected 2 car
      message: This device is connected to android auto.
      data:
        car_ui: true
        notification_icon: mdi:car
        channel: Auto
        importance: high
  mode: single
- id: '1708473160035'
  alias: 'Battery replacement '
  description: ''
  use_blueprint:
    path: andrew-codechimp/battery_notes_battery_replaced.yaml
- id: '1775773377422'
  alias: 'TV Licht schalter '
  description: ''
  triggers:
  - domain: mqtt
    device_id: aec37ed37b3eb90d7aaed0a989c61def
    type: action
    subtype: 'off'
    trigger: device
  - domain: mqtt
    device_id: aec37ed37b3eb90d7aaed0a989c61def
    type: action
    subtype: 'on'
    trigger: device
  conditions: []
  actions:
  - action: light.toggle
    metadata: {}
    target:
      entity_id: light.tv_licht
    data: {}
  mode: single
- id: '1775773676360'
  alias: Lichthelligkeit per Rad steuern
  description: ''
  triggers:
  - domain: mqtt
    device_id: aec37ed37b3eb90d7aaed0a989c61def
    type: action
    subtype: brightness_move_to_level
    metadata: {}
    trigger: device
  conditions: []
  actions:
  - alias: Update light brightness
    action: light.turn_on
    target:
      entity_id: light.tv_licht
    data:
      brightness_step: 10
  mode: restart
- id: '1782164572274'
  alias: Bird detection
  description: ''
  triggers:
  - trigger: webhook
    allowed_methods:
    - POST
    - PUT
    local_only: true
    webhook_id: notify-bird-detection-birdnet
  conditions: []
  actions:
  - action: script.notify_engine
    metadata: {}
    data:
      who: home
      tag_id: information
      value1: "Time: {{ trigger.json.metadata.bg_detection_time }}   \nCamera: {{
        trigger.json.metadata.location }}  \nConfidence: {{ trigger.json.metadata.bg_confidence_percent
        }}\n  "
      title: "\U0001F99C {{ trigger.json.metadata.species }} Detected!"
      group: bird
      icon: mdi:bird
  mode: single
