---
# Parents Away
alias: parentsAway
id: 03a20f50-86fa-4a6f-915d-325ae9f3b36f
description: "Automation when parents are away"
trigger:
  - platform: state
    entity_id: group.parents
    to: "not_home"
    for:
      hours: 0
      minutes: 1
      seconds: 0
condition: []
action:
  - action: switch.turn_on
    target:
      entity_id: switch.kamera_steckdose_wz
mode: single
