---
# Automatisierung zum Rolladen öffnen, damit Abends gelüftet werden kann,
alias: RolladenLueften
id: 907a7f7e-836e-4a75-b98c-a793f0da9534
description: "Öffnet Rolladen zum Lüften"
trigger:
  - platform: template
    value_template: |
      {{ state_attr( "weather.home", "temperature" ) < state_attr("climate.daikinap90134", "current_temperature") }}
condition:
  - condition: state
    entity_id: binary_sensor.nacht
    state: "off"
  - condition: numeric_state
    entity_id: cover.rollladen_schlafzimmer
    attribute: current_position
    below: "40"
  - condition: state
    entity_id: input_boolean.lueften_aktiv
    state: "on"
  - condition: or
    conditions:
      - below: "23"
        entity_id: sensor.daikinap90134_outside_temperature
        condition: numeric_state
      - below: "23"
        entity_id: weather.home
        attribute: temperature
        condition: numeric_state
  - condition: not
    conditions:
      - condition: state
        entity_id: weather.home
        state: "sunny"

action:
  - service: cover.open_cover
    data: {}
    target:
      entity_id: cover.rollladen_schlafzimmer
mode: single
