---
# Work Restaurant
resource_template: "{{ states('input_text.serverurl') }}/local/browserless/work_restaurant.html"
scan_interval: 0
timeout: 30
log_response: true
method: GET
name: Work Meals
sensor:
  - unique_id: work_meals
    name: "Kantinenessen"
    select: "app-menus h1" # this gives the title (e.g. date or menu heading)
    icon: mdi:silverware-fork-knife
    attributes:
      - name: "One"
        select: "app-category:nth-of-type(1) .name-column > span"
      - name: "One two"
        select: "app-category:nth-of-type(2) .name-column > span"
      - name: "Three"
        select: "app-category:nth-of-type(3) .name-column > span"
      - name: "Four"
        select: "app-category:nth-of-type(4) .name-column > span"
      - name: "Five"
        select: "app-category:nth-of-type(5) .name-column > span"
button:
  - unique_id: work_meals_refresh_button
    name: "Refresh work meals"
