---
# Work Restaurant
resource_template: "{{ states('input_text.serverurl') }}/local/browserless/work_restaurant.html"
scan_interval: 0
timeout: 30
log_response: true
method: GET
name: Work Meals
sensor:
  - unique_id: work_meal_one
    name: "Essen One"
    select: "app-category:nth-of-type(1) .name-column > span"
    value_template: "{{ value }}"
    attributes:
      - name: image
        value_template: "/local/downloaded/work_meals/one.png"

  - unique_id: work_meal_one_two
    name: "Essen One Two"
    select: "app-category:nth-of-type(2) .name-column > span"
    value_template: "{{ value }}"
    attributes:
      - name: image
        value_template: "/local/downloaded/work_meals/one_two.png"

  - unique_id: work_meal_three
    name: "Essen Three"
    select: "app-category:nth-of-type(4) .name-column > span"
    value_template: "{{ value }}"
    attributes:
      - name: image
        value_template: "/local/downloaded/work_meals/three.png"

  - unique_id: work_meal_four
    name: "Essen Four"
    select: "app-category:nth-of-type(5) .name-column > span"
    value_template: "{{ value }}"
    attributes:
      - name: image
        value_template: "/local/downloaded/work_meals/four.png"

  - unique_id: work_meal_five
    name: "Essen Five"
    select: "app-category:nth-of-type(6) .name-column > span"
    value_template: "{{ value }}"
    attributes:
      - name: image
        value_template: "/local/downloaded/work_meals/five.png"
button:
  - unique_id: work_meals_refresh_button
    name: "Refresh work meals"
