save_current_target_temperature:
  name: Save target temperature
  description: Save the current target temperature for later use.
  target:
    entity:
      domain: climate
      integration: better_thermostat

restore_saved_target_temperature:
  name: Restore target temperature
  description: Restore the previously saved target temperature.
  target:
    entity:
      domain: climate
      integration: better_thermostat

reset_heating_power:
  name: Reset heating power
  description: Reset the heating power to its default value.
  target:
    entity:
      domain: climate
      integration: better_thermostat

set_temp_target_temperature:
  name: Set temporary (ECO) target temperature
  description: Set a temporary target temperature and save the current temperature.
  fields:
    temperature:
      name: Temperature
      description: New target temperature to set
      required: true
      selector:
        number:
          min: 0
          max: 35
          step: 0.5
          mode: box
          unit_of_measurement: °C
  target:
    entity:
      domain: climate
      integration: better_thermostat
