---
# check for shopping list items in alexa
alias: CheckAlexaCommand
id: ec5476f5-ecd5-4c4c-86f2-cf052679bb9d
description: ""
triggers:
  - trigger: state
    entity_id: sensor.alexa_last_call_command
conditions: []
actions:
  - variables:
      last_call: "{{ trigger.to_state.state }}"
  - action: ai_task.generate_data
    data:
      entity_id: ai_task.openai_ai_task
      task_name: check for shopping list items
      instructions: |
        You are an intelligent assistant analyzing voice commands.
        Your goal is to extract shopping list items ONLY if the user explicitly wants to add something to a shopping list.

        CRITICAL RULES:
        1. Ignore Smart Home commands (e.g., "turn on lights", "close blinds", "set temperature", "play music"). These are NOT shopping requests.
        2. Only return true if the intent is to buy, purchase, or add an item (e.g., "add milk", "we need butter", "put apples on the list").
        3. If the input is ambiguous or purely a command like "light off", assume it is NOT a shopping item.

        Text to analyze:: {{ last_call }}
      structure:
        shop:
          description: Is this strictly a request to add an item to a shopping list? (False for device controls like lights/switches)
          required: true
          selector:
            boolean: null
        grocery:
          description: The specific item to buy (e.g., 'milk'). Extract the noun only.
          required: true
          selector:
            text: null
    response_variable: response
  - if:
      - condition: template
        value_template: "{{  response.data.shop == true }}"
    then:
      - action: todo.add_item
        target:
          entity_id: todo.picnic_einkaufswagen
        data:
          item: "{{ response.data.grocery  }}"
mode: parallel
