---
# Room analysis
alias: Climate analysis
id: 7954ce4c-46ba-4224-8f18-e1b470550b92
description: ""
triggers:
  - trigger: time_pattern
    minutes: /30
conditions:
  - condition: state
    entity_id: group.residents
    state: "home"
actions:
  - action: ai_task.generate_data
    data:
      entity_id: ai_task.google_ai_task
      task_name: climate_analysis
      instructions: |
        ### ROLE
        You are an expert for indoor climate and HVAC systems. Analyze the provided sensor data and generate a summary in German.

        ### INPUT DATA
        - Home_Global:
            Temp: {{ states('sensor.wohnungstemperatur') | float(-99) }} °C
            Humidity: {{ states('sensor.wohnungsfeuchtigkeit') | float(-1) }} %
        - Outdoors:
            Temp: {{ states('sensor.temperatur') | float(-99) }} °C
            Humidity: {{ states('sensor.luftfeuchtigkeit') | float(-1) }} %
            Dew Point: {{ states('sensor.aussen_thermal_comfort_taupunkt') | float(-99) }} °C
        - Office:
            Temp: {{ states('sensor.luftqualitat_buro_temperature') | float(-99) }} °C
            Humidity: {{ states('sensor.luftqualitat_buro_humidity') | float(-1) }} %
            VOC: {{ states('sensor.luftqualitat_buro_voc_index') | int(-1) }}
            PM25: {{ states('sensor.luftqualitat_buro_pm25') | float(-1) }} µg/m³
        - Living_Room:
            Temp: {{ states('sensor.wohnzimmertemperatur') | float(-99) }} °C
            Humidity: {{ states('sensor.wohnzimmerluftfeuchtigkeit') | float(-1) }} %
            Dew Point: {{ states('sensor.wohnzimmer_thermal_comfort_taupunkt') | float(-99) }} °C
        - Bedroom:
            Temp: {{ states('sensor.schlafzimmertemperatur') | float(-99) }} °C
            Humidity: {{ states('sensor.schlafzimmerluftfeuchtigkeit') | float(-1) }} %
            Dew Point: {{ states('sensor.schlafzimmer_thermal_comfort_taupunkt') | float(-99) }} °C

        ### LOGIC RULES (Ventilation)
        1. Compare Absolute Humidity (physically):
          - If Outdoor Temp is significantly lower (>5°C difference) than Indoor Temp, assume outdoor air is drier even if relative humidity is higher (up to 90%).
          - Recommendation: "Lüften empfohlen" (Ventilation recommended) to reduce indoor humidity.
        2. Air Quality:
          - If VOC > 250 OR PM2.5 > 20 -> Priority Recommendation: "Lüften wegen Luftqualität dringend empfohlen".

        ### OUTPUT INSTRUCTIONS
        - Language: German
        - Tone: Professional, concise, helpful.
        - Format per room:
          1. Current State (e.g., "Angenehm warm", "Zu feucht").
          2. Specific Reasoning (e.g., "VOC erhöht").
          3. Actionable Recommendation (Start with "Empfehlung:").
        - Missing Data: If values are -99 or -1, state "Daten nicht verfügbar".

      structure:
        house:
          description: "Summary for the whole house"
          required: true
          selector:
            text:
        office:
          description: "Analysis for the office"
          required: true
          selector:
            text:
        living:
          description: "Analysis for the living room"
          required: true
          selector:
            text:
        sleep:
          description: "Analysis for the bedroom"
          required: true
          selector:
            text:
    response_variable: response
  - parallel:
      - action: input_text.set_value
        target:
          entity_id: input_text.klima_analyse
        data:
          value: "{{ response.data.house }}"
      - action: input_text.set_value
        target:
          entity_id: input_text.arbeitszimmer_klima_analyse
        data:
          value: "{{ response.data.office }}"
      - action: input_text.set_value
        target:
          entity_id: input_text.wohnzimmer_klima_analyse
        data:
          value: "{{ response.data.living }}"
      - action: input_text.set_value
        target:
          entity_id: input_text.schlafzimmer_klima_analyse
        data:
          value: "{{ response.data.sleep }}"
mode: single
