---
# work meal ai img
alias: MealImg
description: ""
id: ffe67e29-366b-4661-a0b0-bfea95d4468e
triggers:
  - trigger: state
    entity_id: input_text.work_meal_one
    id: one
  - trigger: state
    entity_id: input_text.work_meal_one_two
    id: one_two
  - trigger: state
    entity_id: input_text.work_meal_three
    id: three
  - trigger: state
    entity_id: input_text.work_meal_four
    id: four
  - trigger: state
    entity_id: input_text.work_meal_five
    id: five
  - trigger: state
    entity_id: input_text.milo_kita_essen_mittwoch
    id: mittwoch
  - trigger: state
    entity_id: input_text.milo_kita_essen_donnerstag
    id: donnerstag
  - trigger: state
    entity_id: input_text.milo_kita_essen_freitag
    id: freitag
  - trigger: state
    entity_id: input_text.mittagessen
    id: mittagessen
conditions:
  - condition: template
    value_template: "{{  states(trigger.entity_id) != 'unavailable' }}"
actions:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.id in ['one', 'one_two', 'three', 'four', 'five'] }}"
        sequence:
          - variables:
              directory: work_meals
      - conditions:
          - condition: template
            value_template: "{{ trigger.id in ['mittwoch', 'donnerstag', 'freitag'] }}"
        sequence:
          - variables:
              directory: kita_meals
      - conditions:
          - condition: template
            value_template: "{{ trigger.id in ['frühstück', 'mittagessen', 'abendessen'] }}"
        sequence:
          - variables:
              directory: meals
    default:
      - variables:
          directory: meals
  - action: ai_task.generate_image
    data:
      task_name: "Meal {{ trigger.id }}"
      instructions: |-
        Eine Nahaufnahme (Close-Up shot) in hoher Qualität von:
        {{ trigger.to_state.state }}
        Der Stil ist moderne Food-Fotografie.
        Die Beleuchtung ist warm und natürlich, um die Texturen des Essens hervorzuheben.
        Der Fokus liegt knackig scharf auf dem Hauptgericht, mit einem schönen, unscharfen Hintergrund (Bokeh).
        Bitte keine Texte auf die Bilder generieren.
        Es sieht köstlich und frisch zubereitet aus.
      entity_id: ai_task.google_ai_task
    response_variable: meal

  - action: downloader.download_file
    data:
      overwrite: true
      url: "http://localhost:8123{{ meal.url }}"
      filename: "{{ trigger.id }}.png"
      subdir: "{{ directory }}"
mode: parallel
