---
# work meal ai img
alias: MealImg
description: ""
id: ffe67e29-366b-4661-a0b0-bfea95d4468e
triggers:
  - trigger: state
    entity_id:
      - input_text.work_meal_one
      - input_text.work_meal_one_two
      - input_text.work_meal_three
      - input_text.work_meal_four
      - input_text.work_meal_five
      - input_text.milo_kita_essen_mittwoch
      - input_text.milo_kita_essen_donnerstag
      - input_text.milo_kita_essen_freitag
      - input_text.mittagessen_montag
      - input_text.mittagessen_dienstag
      - input_text.mittagessen_mittwoch
      - input_text.mittagessen_donnerstag
      - input_text.mittagessen_freitag
      - input_text.mittagessen_samstag
      - input_text.mittagessen_sonntag
conditions:
  - condition: template
    value_template: "{{  states(trigger.entity_id) != 'unavailable' }}"
actions:
  - variables:
      directory: >
        {% set eid = trigger.entity_id %}
        {% if 'work' in eid %}
          work_meals
        {% elif 'kita' in eid %}
          kita_meals
        {% else %}
          meals
        {% endif %}
      clean_name: "{{ trigger.entity_id.split('.')[1] }}"
  - action: ai_task.generate_image
    data:
      task_name: "Meal {{ clean_name }}"
      instructions: |-
        Eine Nahaufnahme (Close-Up shot) in hoher Qualität von:
        {{ trigger.to_state.state }}
        Der Stil ist moderne Food-Fotografie.
        Die Beleuchtung ist warm und natürlich, um die Texturen des Essens hervorzuheben.
        Der Fokus liegt knackig scharf auf dem Hauptgericht, mit einem schönen, unscharfen Hintergrund (Bokeh).
        Bitte keine Texte auf die Bilder generieren.
        Es sieht köstlich und frisch zubereitet aus.
      entity_id: ai_task.google_ai_task
    response_variable: meal

  - action: downloader.download_file
    data:
      overwrite: true
      url: "http://localhost:8123{{ meal.url }}"
      filename: "{{ clean_name }}.png"
      subdir: "{{ directory }}"
mode: parallel
