---
# AI morning briefing
alias: MorningBriefing
description: ""
id: ca2ea9b9-5ef6-4867-af35-4ce299c817ae
triggers:
  - platform: time
    at: "08:00:00"
conditions:
  - condition: state
    entity_id: input_boolean.ai_morning_briefing
    state: "on"
actions:
  - action: ai_task.generate_data
    data:
      entity_id: ai_task.openai_ai_task
      task_name: morning briefing
      instructions: |
        Task: Generate a short morning briefing in German.

        Include following data:
          - current date: {{ as_timestamp(states('sensor.date_time_iso')) | timestamp_custom('%A %B %-d, %I:%M %p') }}
          - Outdoor temperature: {{ states('sensor.daikinap90134_outside_temperature') }}°C
          - Weather condition: {{ states('weather.home') }}
          - Is today a work day?: {{ states('binary_sensor.workday_sensor') }}

        Also include ONE verified historical fact that happened on this date.
          - Search online for it.
          - Use only reliable, factual sources.

        Style:
          - Language: German
          - Tone: friendly, slightly funny, natural
          - Keep it concise and readable.

        ⚠️ Output rule:
        - The entire response must be **under 200 characters total**.
        - If it would exceed this, shorten or omit details.
        - No extra explanations or notes.

    response_variable: response
  - action: input_text.set_value
    target:
      entity_id: input_text.ai_morning_briefing
    data:
      value: "{{ response.data }}"
mode: parallel
