---
# AI Weather picture
alias: WeatherAIPic
description: ""
id: c2e4550d-1016-4ff5-bff6-9d73d092a773
triggers:
  - trigger: state
    entity_id: weather.home
conditions: []
actions:
  - action: ai_task.generate_image
    response_variable: generated_image
    data:
      task_name: "Weather Picture"
      instructions: >-
        Show the town of {{ state_attr('weather.home', 'friendly_name') }} in Germany in the picture. Include a dog in the
        image wearing clothing which reflects the weather. The dog is a famous
        tv-presenter who is presenting the weather-report live on-air right now.

        It is {{ states('weather.home') }}, but keep in mind that the sun
        is {{ states('sun.sun') | replace('_', ' the ')}}.
        The temperature is {{ state_attr('weather.home','temperature') }}{{ state_attr('weather.home','temperature_unit') }}.

        Make it as realistic as possible
      entity_id: ai_task.google_ai_task
  - alias: "Send out a manual event to update the image entity"
    event: new_weather_image
    event_data:
      url: '{{ generated_image.url }}'
mode: parallel
