---
# Switch Cameras on/off
id: 4ea8098a-37d6-4980-8ca9-1bea1463774b
alias: securityCamsSwitch
description: ""
trigger:
  - platform: state
    entity_id: input_boolean.security_cameras
condition: []
action:
  - if:
      - condition: state
        entity_id: input_boolean.security_cameras
        state: "on"
    then:
      - action: switch.turn_on
        target:
          entity_id:
            - switch.kamera_steckdose_wz
            - switch.flur_cam_stecker
        data: {}
    else:
      - action: switch.turn_off
        target:
          entity_id:
            - switch.kamera_steckdose_wz
            - switch.flur_cam_stecker
        data: {}
mode: single
