---
# Snapshot when door opens
id: 87a6c36c-7123-4083-bd32-0927d6fa36c4
alias: snapshotOnDoorChange
description: ""
trigger:
  - platform: state
    entity_id: binary_sensor.hausture_window
    to: "on"
condition:
  - condition: state
    entity_id: switch.flur_cam_stecker
    state: "on"
action:
  - action: browser_mod.popup
    data:
      content:
        type: picture-entity
        entity: camera.flurcam
        show_state: false
        show_name: false
        camera_view: live
      autoclose: true
      timeout: 30000
      title: Haustüre wurde geöffnet
      size: classic
      allow_nested_more_info: false
  - variables:
      timestamp: '{{ state_attr("camera.flurcam", "friendly_name") }}_{{ now().strftime("%Y%m%d-%H%M%S") }}'
  - variables:
      file_path: "/media/{{ timestamp }}.mp4"
      pic_path: "{{ timestamp }}.jpg"
      start: "{{ now() }}"
  - action: camera.snapshot
    target:
      entity_id: camera.flurcam
    data:
      filename: "/config/www/cams/{{ pic_path }}"
  - variables:
      end: "{{ now() }}"
  - event: cam_event
    event_data:
      event: Haustüre geöffnet
      starts: "{{ start }}"
      ends: "{{ end }}"
      summary: "Haustüre wurde geöffnet"
      key_frame: "/local/cams/{{ pic_path }}"
      camera: camera.flurcam
  - action: camera.record
    target:
      entity_id:
        - camera.flurcam
    data:
      duration: 5
      filename: "{{ file_path }}"

mode: single
