---
id: 1838588e-2696-4082-8f5b-ef025daf94c4
alias: alarmOnDoorOpen
description: "Alarm auslösen, wenn die Tür geöffnet wird."
trigger:
  - platform: state
    entity_id: lock.hausture
    from: locked
    to: unlocked
condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: armed_away
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: armed_home
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: armed_vacation
action:
  - service: alarm_control_panel.alarm_trigger
    target:
      entity_id: alarm_control_panel.home_alarm
  - service: script.notify_engine
    data:
      title: "🚪 Türe 🚪"
      value1: "{{ trigger.to_state.attributes.friendly_name }} wurde geöffnet."
      who: "home"
      tag_id: "alert"
      group: "Alarm"
mode: single
