---
id: b06e36c7-31a2-429d-88e5-70fdcf2d72c7
alias: unarmAlarm
description: Alarm automatisch abschalten
trigger:
  - platform: state
    entity_id: group.residents
    to: "home"
condition:
  - condition: state
    entity_id: alarm_control_panel.alarmo
    state: "armed_away"
action:
  - service: alarm_control_panel.alarm_disarm
    entity_id: alarm_control_panel.alarmo
    data:
      code: !secret alarm_code
