---
# Holiday automation
alias: UrlaubsmodusAutom
id: d671c363-5a0c-4f56-b8ff-857234b23b61
description: "Schaltet das Smart Home System in den Urlaubsmodus."
trigger:
  - platform: state
    entity_id: alarm_control_panel.alarmo

condition: []
action:
  - if:
      - condition: state
        entity_id: alarm_control_panel.alarmo
        state: "armed_vacation"
    then:
      - service: input_boolean.turn_on
        entity_id: input_boolean.holiday_mode
  - if:
      - condition: state
        entity_id: alarm_control_panel.alarmo
        state: "disarmed"
      - condition: state
        entity_id: input_boolean.holiday_mode
        state: "on"
    then:
      - service: input_boolean.turn_off
        entity_id: input_boolean.holiday_mode
mode: single
