---
# Notiy if outside plants need watering
alias: WateringNotifOutdoor
id: 1458fb06-3f77-4669-8e72-0a7ec224be45
description: "Benachrichtigt, ob die Pflanzen draußen gegossen werden müssen."
trigger:
  - platform: time
    at: input_datetime.watering_time
condition:
  - condition: not
    alias: "Check if it is currently raining or will rain soon"
    conditions:
      - condition: state
        alias: "Currently raining"
        entity_id: weather.home
        state: "rainy"
      - condition: template
        alias: "Will it rain soon"
        value_template: >
          {% set days = 1 %}
          {{ 'rainy' in state_attr('weather.home', 'forecast')[:days] | map(attribute='condition') | list }}
  - condition: numeric_state
    alias: "Rained less than 1h last day"
    entity_id: sensor.rained_last_day
    below: 1
  - condition: state
    alias: "Holiday mode is off"
    entity_id: input_boolean.holiday_mode
    state: "off"
  - condition: or
    alias: "Only in specific seasons"
    conditions:
      - condition: state
        alias: "Spring"
        entity_id: sensor.season
        state: "spring"
      - condition: state
        alias: "Summer"
        entity_id: sensor.season
        state: "summer"
action:
  - action: script.notify_engine
    alias: "Send plant watering notification"
    data:
      title: |
        🌊🌿 Gießen 🌊🌿
      value1: |
        Pflanzen müssen heute gegossen werden!
      who: "home"
      tag_id: "information"
      group: "Pflanzen"
mode: single
