---
#
sensor:
  name: "Birdnet Daily"
  unique_id: birdnet_daily
  command: 'curl -s http://192.168.0.76:8088/api/v2/analytics/species/daily | jq "{birds: .}"'
  scan_interval: 300
  value_template: "{{ value_json.birds | length }}"
  json_attributes:
    - birds
