---
# Notiy if tasks due
alias: TasksNotif
id: afa5aa6b-7cf4-43bb-bb47-d37601433dea
trigger:
  - platform: time
    at: input_datetime.chores_notif_time
condition:
  - condition: not
    conditions:
      - condition: state
        entity_id: sensor.grocy_tasks
        state: "0"
action:
  - alias: CalculateFilteredTasks
    variables:
      filtered_tasks: >
        {% set todos = state_attr('sensor.grocy_tasks', 'tasks') | default([], true) %}
        {% set now_date = now().date() %}
        {% set upcoming_date = (now() + timedelta(days=10)).date() %}

        {% set filtered = namespace(tasks=[]) %}
        {% for task in todos %}
          {% if task.due_date is defined and task.due_date %}
            {% set due_date = as_datetime(task.due_date).date() %}
            {% if due_date >= now_date and due_date <= upcoming_date %}
              {% set filtered.tasks = filtered.tasks + [task] %}
            {% endif %}
          {% endif %}
        {% endfor %}

        {{ filtered.tasks | sort(attribute='category.name') }}
  - alias: StopIfNoTasksDue
    condition: template
    value_template: "{{ filtered_tasks | length > 0 }}"
  - alias: SendNotification
    service: script.notify_engine
    data:
      title: "📑 ToDo's in den nächsten Tagen 📑"
      value1: >
        {% set current_cat = '' %}
        Folgende ToDo's stehen in den nächsten 10 Tagen an:

        {%- for task in filtered_tasks %}
          {%- set cat = task.category.name if task.category is defined and task.category.name is defined else 'Ohne Kategorie' %}
          {%- if cat != current_cat %}
        📑 Kategorie: {{ cat }}
            {%- set current_cat = cat %}
          {%- endif %}
        - {{ task.name }}
          📝 {{ task.description or '' }}
          👤 {{ task.assigned_to_user.display_name if task.assigned_to_user is defined and task.assigned_to_user.display_name is defined else 'Unbekannt' }}
          🗓️ {{ as_timestamp(task.due_date) | timestamp_custom('%d.%m.%Y %H:%M') }}
        {%- endfor %}
      who: "home"
      tag_id: "information"
      group: "Hausarbeiten"
mode: single
