---
title: Einstellungen
path: settings
icon: mdi:cog
subview: true
type: sections
max_columns: 3
theme: ios-dark-mode-blue-red
header:
  layout: center
  badges_position: top
badges:
  - type: custom:mushroom-template-badge
    icon: mdi:arrow-left
    tap_action:
      action: navigate
      navigation_path: start
sections:
  - type: grid
    cards:
      - entity: input_boolean.audible_notifications
        type: custom:mushroom-entity-card
        name: Sound
        layout: vertical
        tap_action:
          action: toggle
      - entity: input_boolean.text_notifications
        type: custom:mushroom-entity-card
        name: Text
        layout: vertical
        tap_action:
          action: toggle
      - entity: input_boolean.presence_light
        type: custom:mushroom-entity-card
        name: Licht
        layout: vertical
        tap_action:
          action: toggle
  - type: grid
    cards:
      - entity: input_boolean.lueften_aktiv
        type: custom:mushroom-entity-card
        name: Lüften
        layout: vertical
        tap_action:
          action: toggle
      - entity: input_boolean.sonnen_wegblenden_schlafen_aktiv
        type: custom:mushroom-entity-card
        name: Sonnenaufgang
        layout: vertical
        tap_action:
          action: toggle
      - entity: input_boolean.sonnen_schutz_aktiv
        type: custom:mushroom-entity-card
        name: Sonnenschutz
        layout: vertical
        tap_action:
          action: toggle
      - entity: input_boolean.wecker_aktiv
        type: custom:mushroom-entity-card
        name: Aufstehen/Wecker
        layout: vertical
        tap_action:
          action: toggle
      - entity: input_boolean.automatic_cleaning
        type: custom:mushroom-entity-card
        layout: vertical
        name: Saugroboter
        tap_action:
          action: toggle
  - type: grid
    cards:
      - entity: input_datetime.chores_notif_time
        type: custom:mushroom-entity-card
        layout: vertical
        tap_action:
          action: more-info
      - entity: input_datetime.watering_time
        type: custom:mushroom-entity-card
        layout: vertical
        tap_action:
          action: more-info
      - entity: input_number.strompreis
        type: custom:mushroom-entity-card
        layout: vertical
      - entity: input_number.wasserpreis_pro_m3
        type: custom:mushroom-entity-card
        layout: vertical
      - entity: input_select.milo_person_sync
        type: custom:mushroom-select-card
        secondary_info: last-changed
        layout: vertical
      - entity: input_select.maja_person_sync
        type: custom:mushroom-select-card
        secondary_info: last-changed
        layout: vertical
