---
alias: Abfallbenachrichtigung
id: f9432fc2-3051-4325-b8d6-1ba50259050b
description: "Benachrichtigt wenn Abfall abgeholt wird."
trigger:
  - platform: state
    entity_id:
      - sensor.restmull
      - sensor.papiertonne
      - sensor.schadstoffe
    attribute: "DaysTo"
    to: 0
    id: heute
  - platform: state
    entity_id:
      - sensor.restmull
      - sensor.papiertonne
      - sensor.schadstoffe
    attribute: "DaysTo"
    to: 1
    id: morgen

condition:
  - condition: state
    entity_id: input_boolean.holiday_mode
    state: "off"
action:
  - service: script.notify_engine
    data:
      title: |
        🗑️ Abfall 🗑️
      value1: |
        {{ trigger.to_state.attributes.friendly_name }} wird {{ trigger.id }} abgeholt.
      who: "home"
      tag_id: "information"
      group: "Abfall"
mode: parallel
