---
# Festnetzbenachrichtigung
alias: Festnetzbenachrichtigung
id: 2779b29f-8710-4a7b-adc8-03ec212b4ffb
description: "Benachrichtigen bei verpassten anrufen"
trigger:
  - platform: state
    entity_id: sensor.fritz_box_7590_ax_anrufmonitor_telefonbuch
    from: ringing
condition: []
action:
  - if:
      - condition: template
        value_template: "{{ trigger.to_state.state == 'idle' }}"
    then:
      - service: script.notify_engine
        data:
          title: |
            📞 Verpasster Anruf 📞
          value1: |
            {{ states('sensor.callmon_name') }} ({{ states('sensor.callmon_number') }}) hat angerufen.
          who: "home"
          tag_id: "information"
          group: "Telephone"
  - if:
      - condition: template
        value_template: "{{  trigger.to_state.state == 'talking' }}"
      - condition: template
        value_template: "{{ trigger.to_state.attributes.device == '40' }}"
    then:
      - service: script.notify_engine
        data:
          title: |
            📞 Verpasster Anruf - Weiterleitung AB 📞
          value1: |
            {{ states('sensor.callmon_name') }} ({{ states('sensor.callmon_number') }}) hat angerufen und wird jetzt auf den AB umgeleitet.
          who: "home"
          tag_id: "information"
          group: "Telephone"

mode: single
