---
# Grocy notifications
alias: GrocyNotifExpired
id: ba321099-add9-41a4-bc53-0699f29977e6
description: "Benachrichtigt, wenn Produkte ablaufen sind"
trigger:
  - platform: state
    entity_id: binary_sensor.grocy_expired_products
    attribute: count

condition:
  - condition: state
    entity_id: binary_sensor.grocy_expired_products
    state: "on"
action:
  - service: script.notify_engine
    data:
      title: |
        🥫☠️ Produkte sind abgelaufen 🍲☠️
      value1: >-
        {% set expiredProducts = state_attr("binary_sensor.grocy_expired_products", "expired_products")%}
        {% set expiredCount = state_attr("binary_sensor.grocy_expired_products", "count")%}

        Folgende {{ expiredCount }} Produkte sind abgelaufen:
        {{- '\n' -}}
        {% for i in expiredProducts %}
        - {{ i.name }} {{ as_timestamp(i.best_before_date) | timestamp_custom('%d.%m.%Y') }}
        {{- '\n' -}}
        {% endfor %}

      who: "home"
      tag_id: "information"
      group: "Food"
mode: single
