---
# Holiday automation
alias: UrlaubsmodusAutom
id: 7c88607a-9f86-45aa-852c-601e2c76385e
description: "Schaltet das Smart Home System in den Urlaubsmodus."
trigger:
  - platform: state
    entity_id: input_boolean.holiday_mode

condition: []
action:
  - if:
      - condition: state
        entity_id: input_boolean.holiday_mode
        state: "on"
    then:
      - service: script.notify_engine
        data:
          title: |
            Urlaubsmodus eingeschaltet
          value1: "🌴"
          who: "home"
          tag_id: "information"
          group: "Urlaub"
      - service: light.turn_off
        data: {}
        target:
          entity_id: light.kameralichter

    else:
      - service: script.notify_engine
        data:
          title: |
            Urlaubsmodus ausgeschaltet
          value1: "🌴"
          who: "home"
          tag_id: "information"
          group: "Urlaub"
      - service: light.turn_on
        data: {}
        target:
          entity_id: light.kameralichter
mode: single
