---
# MeteoAlarm Warnungen
alias: MeteoAlarm
id: 40db0999-dd04-4b40-b5d3-58684fc9895f
description: "Meteo Alarm"
trigger:
  - platform: state
    entity_id: binary_sensor.meteoalarm
    to: "on"
condition: []
action:
  - action: script.notify_engine
    data:
      title: "ðŸŒ©ï¸ {{state_attr('binary_sensor.meteoalarm', 'headline')}} ðŸŒ©ï¸"
      value1: >-
        {{state_attr('binary_sensor.meteoalarm', 'description')}}

        {{state_attr('binary_sensor.meteoalarm', 'effective')}}

        *Handlungsempfehlung:*
        {{state_attr('binary_sensor.meteoalarm', 'instruction')}}
      who: "family"
      tag_id: "information"
      # group: "Wetter"
