---
# nina Warnungen
alias: NINA Warnungen
id: a708dd34-6dd1-4745-a971-debf244734a5
description: "NINA Warnungen"
trigger:
  - platform: state
    entity_id: binary_sensor.warning_home_1
    to: "on"
  - platform: state
    entity_id: binary_sensor.warning_home_2
    to: "on"
  - platform: state
    entity_id: binary_sensor.warning_home_3
    to: "on"
  - platform: state
    entity_id: binary_sensor.warning_home_4
    to: "on"
  - platform: state
    entity_id: binary_sensor.warning_home_5
    to: "on"
condition:
  - condition: state
    entity_id: input_boolean.holiday_mode
    state: "off"
action:
  - service: script.notify_engine
    data:
      title: "🌩️  {{ trigger.to_state.attributes.headline }} (NINA) 🌩️"
      value1: >-
        {% set attributes = trigger.to_state.attributes %}
        {{ attributes.description }}

        *Zeitraum*
        ⏰ _{{ as_datetime(attributes.start)  ~ " - " ~  as_datetime(attributes.expires) }}_

        *Handlungsempfehlung*
          {{ attributes.recommended_actions }}

        *Warnung von:*
          {{ attributes.sender }}

        *Betroffene Bereiche*
          {{ attributes.affected_areas }}
      who: "home"
      tag_id: "information"
      group: "Wetter"
