---
# Pollen notification
# sensor.pollenflug_graeser_112
alias: Pollenbenachrichtigung
id: 72ec3377-7e22-4ba2-b9a3-f3ef82261ade
description: "Benachrichtigt wenn Pollen fliegen auf die einer im Haus allergisch ist."
trigger:
  - platform: state
    entity_id:
      - sensor.pollenflug_graeser_112
condition:
  - condition: numeric_state
    entity_id: sensor.pollenflug_graeser_112
    above: 0
action:
  - service: script.notify_engine
    data:
      title: |
        ☠️🌺 Pollenflug 🌺☠️
      value1: |
        {{ trigger.to_state.attributes.friendly_name }} haben heute eine "{{  trigger.to_state.attributes.state_today_desc  }}"
        und morgen eine "{{ trigger.to_state.attributes.state_tomorrow_desc  }}".
        Status heute: {{ trigger.to_state.state  }}
        Status morgen: {{ trigger.to_state.attributes.state_tomorrow  }}
      who: "home"
      tag_id: "information"
      group: "Health"
mode: single
