---
alias: "Einkaufsbenachrichtigung"
id: 9c0cb04f-09bc-49f6-a9d8-e5ec3ff73f2b
description: Einkaufsbenachrichtigung
trigger:
  - platform: state
    entity_id:
      - zone.rewe
      - zone.kaufland
    from: "0"
    for:
      hours: 0
      minutes: 3
      seconds: 0
    id: picnic_einkaufswagen
  - platform: state
    entity_id:
      - zone.getranke_markt
    from: "0"
    for:
      hours: 0
      minutes: 3
      seconds: 0
    id: getranke
  - platform: state
    entity_id:
      - zone.dm
    from: "0"
    for:
      hours: 0
      minutes: 3
      seconds: 0
    id: dm_einkaufen

condition: []

action:
  - variables:
      list_id: "todo.{{ trigger.id }}"
  - condition: template
    value_template: "{{ states(list_id) | int > 0 }}"
  - action: todo.get_items
    target:
      entity_id: "{{ list_id }}"
    data:
      status: needs_action
    response_variable: incompleteItems
  - action: script.notify_engine
    data:
      title: Einkaufsliste - {{ states(list_id) }} Dinge
      value1: |
        {% for i in incompleteItems[list_id]['items'] %}
          - {{ i.summary }} {%
        endfor %}
      who: "home"
      tag_id: information
      group: Einkauf
mode: single
