---
# Automatic send a notification when storage is almost full
# sensor.sky_q_used_storage
alias: SkyQ Festplattenbenachrichtigung
id: d918f790-f21a-4696-a3f5-b119ba806093
description: "Benachrichtigen, dass die Fesplatte fast voll ist."
trigger:
  - platform: numeric_state
    entity_id: sensor.sky_q_used_storage
    attribute: skyq_storage_percent
    above: "90"
condition: []
action:
  - service: script.notify_engine
    data:
      title: |
        💽 Sky Festplatte fast voll 💽
      value1: |
        Die Festplatte vom Sky Reciver hat momentan: {{ states("sensor.sky_q_used_storage") }} GB.
        Das ist eine Auslastung von {{ state_attr("sensor.sky_q_used_storage", "skyq_storage_percent") }} %.
      who: "home"
      tag_id: "information"
      group: "TV"
mode: single
