---
#
alias: "Scheduled flight lands"
trigger:
  platform: event
  event_type: flightradar24_tracked_landed
action:
  - variables:
      title: Flight
      message: >-
        Flight landed {{ trigger.event.data.callsign }} to {{ trigger.event.data.airport_destination_city }}
        [Open FlightRadar](https://www.flightradar24.com/{{ trigger.event.data.callsign }})
  - service: script.notify_engine
    data:
      title: "{{ title }}"
      value1: "{{ message }}"
      who: "home, family"
      tag_id: "information"
      group: "Flights"
  - service: text.set_value
    data:
      value: "{{ trigger.event.data.aircraft_registration }}"
    target:
      entity_id: text.flightradar24_remove_from_track
