---
# Update notif
alias: Update Available Notification
id: 11defef9-9e5c-41ff-8657-d5a79f384861
trigger:
  - platform: state
    entity_id: binary_sensor.home_assistant_versions_update_available
    from: "off"
    to: "on"
action:
  - service: script.notify_engine
    data:
      title: Update available
      value1: >-
        {{ state_attr('binary_sensor.home_assistant_versions_update_available', 'friendly_name')
        }}.
      who: "miguel"
      tag_id: "information"
      group: "System"
mode: single
