---
alias: UVProtectionWindow
id: eafbd24c-50b8-4aaa-9a46-cf7f72f36eca
description: "Benachrichtigt wenn man sich draußen eincremen sollte."
trigger:
  - platform: state
    entity_id:
      - binary_sensor.protection_window
    to: "on"

condition: []
action:
  - service: script.notify_engine
    data:
      title: |
        🌞 UV Warnung ☀️
      value1: |-
        Aktuell sollte man draußen je nach Hauttyp nur zwischen
        {{ states('sensor.skin_type_1_safe_exposure_time') }} {{ state_attr('sensor.skin_type_1_safe_exposure_time', 'unit_of_measurement') }} und
        {{ states('sensor.skin_type_4_safe_exposure_time') }} {{ state_attr('sensor.skin_type_4_safe_exposure_time', 'unit_of_measurement') }} ungeschützt verbringen.
        Bei längeren Aufenthalten bitte schützen.
        Voraussichtliches Ende des Schutzfensters: {{ (state_attr('binary_sensor.protection_window', 'end_time')|as_timestamp(now()) )| timestamp_custom('%H:%M') }}Uhr
      who: "home"
      tag_id: "information"
      group: "weather"
mode: single
