---
# Waschmaschinen Benachrichtigung
alias: WashingNotif
id: 85d51d88-d162-4a4b-b1ee-d09e818afb98
description: "Benachrichtigt wenn die Waschmaschine fertig ist"
trigger:
  - platform: numeric_state
    entity_id: sensor.waschmaschinen_steckdose_power
    below: "1.0"
    for: "00:01:00"
  - platform: state
    entity_id: sensor.waschmaschine_operation_state
    to: "Finished"

condition:
  - condition: state
    entity_id: input_boolean.wash_active
    state: "on"
action:
  - action: script.notify_engine
    data:
      title: |
        🧼 Waschmaschine 🧼
      value1: >-
        {% set cycleConsumption = ( states("sensor.waschmaschinen_steckdose_energy") | float -  states("input_number.wash_cycle_consumption") | float ) %}
        {% set costs = cycleConsumption * states("input_number.strompreis") | float(2) %}
        Waschmaschine ist fertig. Verbrauch {{ cycleConsumption | float|round(2) }} kWh.
        Das macht ca. {{ costs | float|round(2) }} €
      who: "home"
      tag_id: "information"
      group: "Laundry"
  - action: input_boolean.turn_off
    target:
      entity_id: input_boolean.wash_active
  - action: grocy.execute_chore
    data:
      chore_id: "1"
      done_by: "1"
mode: single
