---
# sensor.calendar_destination_location
alias: "Anpassen Fahrzeit aktualisieren"
id: d7ed602b-7a28-4936-9186-f2da48741679
mode: single
trigger:
  - platform: state
    entity_id: sensor.calendar_destination_location
condition: []
action:
  - service: homeassistant.update_entity
    target:
      entity_id: sensor.calendar_location_time
