---
#
alias: "Benachrichtigung vor Termin mit Fahrzeit"
id: f8e94e38-4f30-40f3-9571-011bd66177c5
mode: parallel
trigger:
  - trigger: time
    at:
      entity_id: sensor.calendar_depature_info_time
      offset: "-00:05:00"
condition:
  - condition: template
    value_template: >
      {% set location = state_attr('calendar.familie', 'location') %}
      {{ location is not none and location|length > 0 }}
action:
  - variables:
      title: "{{ state_attr('calendar.familie', 'message') }}"
      start_time: "{{ state_attr('calendar.familie', 'start_time')}}"
      buffer: "{{ states('input_number.fahrzeit_puffer') | int(0) }}"
      location: "{{ state_attr('calendar.familie', 'location') }}"
      travel_time: "{{ states('sensor.calendar_location_time') | int(0) }}"
  - service: script.notify_engine
    data:
      title: "Los geht's!"
      value1: >
        Dein Termin **{{ title }}** beginnt um {{ as_datetime(start_time).strftime('%H:%M') }}.
        Fahrtzeit nach {{ location }}: {{ travel_time }} Minuten (+{{ buffer }} min Puffer).
