---
# Trigged on dawn
alias: Dawn
id: 945c4d4c-02ac-46ec-a478-0094a404269f
description: "Morgendämmerungsautomation"
trigger:
  - platform: time
    at: sensor.sun_next_dawn
condition: []
action: []
mode: single
