---
# Trockner läuft info
alias: DryerActive
id: ee292445-9310-491a-bfde-075737bd1b8e
description: "Setzt den Helfer, wenn der Trockner läuft."
trigger:
  - platform: numeric_state
    entity_id: sensor.trockner_steckdose_power
    above: "15"
    for: "00:01:00"
condition:
  - condition: state
    entity_id: input_boolean.dryer_active
    state: "off"
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.dryer_active
  - service: input_number.set_value
    data_template:
      value: "{{ states('sensor.trockner_steckdose_energy') }}"
      entity_id: input_number.dryer_cycle_consumption
mode: single
