---
# Trigged on dusk
alias: Dusk
id: 36b28e7a-7fdf-4e04-b275-09f577a36913
description: "Abenddämmerungsautomation"
trigger:
  - platform: time
    at: sensor.sun_next_dusk
condition: []
action:
  - if:
      - condition: or
        conditions:
          - condition: state
            entity_id: sensor.season
            state: "autumn"
          - condition: state
            entity_id: sensor.season
            state: "winter"
    then:
      - action: switch.turn_on
        target:
          entity_id: switch.lichterkette
mode: single
