---
# Holiday automation
alias: UrlaubsModus
id: 5899d18e-e2f3-4575-be82-4d81effc7293
description: "Schaltet das Smart Home System in den Urlaubsmodus."
triggers:
  - trigger: state
    entity_id: input_boolean.holiday_mode
conditions: []
actions:
  - if:
      - condition: state
        entity_id: input_boolean.holiday_mode
        state: "on"
    then:
      - action: script.notify_engine
        data:
          title: |
            Urlaubsmodus eingeschaltet
          value1: "🌴"
          who: "home"
          tag_id: "information"
          group: "Urlaub"
      - action: light.turn_off
        target:
          entity_id: light.kameralichter
      - alias: Personen- und Mini-Apps entfernen
        repeat:
          for_each: ["mini", "miguel", "silke", "milo", "finn", "maja"]
          sequence:
            - action: script.awtrix_app
              data:
                app_id: "{{ repeat.item }}"
                show: false
    else:
      - action: script.notify_engine
        data:
          title: |
            Urlaubsmodus ausgeschaltet
          value1: "🌴"
          who: "home"
          tag_id: "information"
          group: "Urlaub"
      - action: light.turn_on
        target:
          entity_id: light.kameralichter
mode: single
