---
# Holiday automation
alias: UrlaubsmodusAutom
id: d671c363-5a0c-4f56-b8ff-857234b23b61
description: "Schaltet das Smart Home System in den Urlaubsmodus."
trigger:
  - platform: state
    entity_id: input_boolean.holiday_mode

condition: []
action:
  - if:
      - condition: state
        entity_id: input_boolean.holiday_mode
        state: "on"
    then:
      - action: script.notify_engine
        data:
          title: |
            Urlaubsmodus eingeschaltet
          value1: "🌴"
          who: "home"
          tag_id: "information"
          group: "Urlaub"
      - action: light.turn_off
        data: {}
        target:
          entity_id: light.kameralichter
      - action: script.awtrix3delapp
        data:
          app_id: "mini"
    else:
      - action: script.notify_engine
        data:
          title: |
            Urlaubsmodus ausgeschaltet
          value1: "🌴"
          who: "home"
          tag_id: "information"
          group: "Urlaub"
      - action: light.turn_on
        data: {}
        target:
          entity_id: light.kameralichter
mode: single
