---
# Maja automatic status
alias: majaButtonGassiStatus
id: 8b746354-94e4-4e07-affa-40b2a01096ac
description: "Maja Gassi wenn Button gedrückt"
trigger:
  - platform: device
    domain: mqtt
    device_id: ee1b9de2827cfce71d276bf85218e92f
    type: action
    subtype: "on"
condition: []
action:
  - action: input_boolean.turn_off
    target:
      entity_id: input_boolean.maja_home
  - delay:
      hours: 1
      minutes: 0
      seconds: 0
      milliseconds: 0
  - action: input_boolean.turn_on
    target:
      entity_id: input_boolean.maja_home
mode: single
