---
# Adblocker state
alias: adblockerState
id: 937b8048-a3a4-4557-9bf1-17e8d1c206bf
description: "Adblocker State"
trigger:
  - platform: state
    entity_id:
      - switch.adguard_home_schutz
condition: []
action:
  - if:
      - condition: state
        entity_id: switch.adguard_home_schutz
        state: "off"
    then:
      - service: timer.start
        target:
          entity_id: timer.werbeblocker_aus
    else:
      - service: timer.cancel
        target:
          entity_id: timer.werbeblocker_aus
mode: single
