---
# Refresh open UV data.
alias: "Update OpenUV data"
id: 7240378c-e4e2-4316-a2d3-604c9b071ae2
trigger:
  platform: time_pattern
  minutes: "/30"
condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: sensor.season
        state: "spring"
      - condition: state
        entity_id: sensor.season
        state: "summer"
  - condition: numeric_state
    entity_id: sun.sun
    value_template: "{{ state.attributes.elevation }}"
    above: 10
action:
  service: homeassistant.update_entity
  target:
    entity_id:
      - binary_sensor.protection_window
      - sensor.current_ozone_level
      - sensor.current_uv_index
      - sensor.current_uv_level
      - sensor.max_uv_index
      - sensor.skin_type_1_safe_exposure_time
      - sensor.skin_type_2_safe_exposure_time
      - sensor.skin_type_3_safe_exposure_time
      - sensor.skin_type_4_safe_exposure_time
