---
# input_boolean.spulmaschine_aktiv
description: "Spülmaschine aktiv"
alias: SpuelmaschineActive
id: a444c0eb-c032-4e9c-b923-6244fe1a24b8
mode: single
triggers:
  - platform: numeric_state
    entity_id: sensor.spulmaschine_leistung
    above: 30
    for: "00:01:00"
    id: "on"
  - platform: numeric_state
    entity_id: sensor.spulmaschine_leistung
    below: 1
    for: "00:01:00"
    id: "off"
conditions: []
actions:
  - if:
      - condition: trigger
        id:
          - "on"
    then:
      - action: input_boolean.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: input_boolean.spulmaschine_aktiv
    else:
      - action: input_boolean.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: input_boolean.spulmaschine_aktiv
