---
# Update travel time
alias: "UpdateTravelTimeSensor"
id: d7ed602b-7a28-4936-9186-f2da48741679
mode: parallel
trigger:
  - alias: "Calendar location changed"
    trigger: state
    entity_id: sensor.calendar_destination_location
    id: location_change
  - trigger: time
    at: "08:00:00"
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    id: workdays_start
  - trigger: time
    at: "16:00:00"
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    id: workdays_end
  - trigger: time_pattern
    minutes: "/15"
    id: periodic
condition: []
action:
  - choose:
      - alias: "Calendar location changed"
        conditions:
          - condition: template
            value_template: "{{ trigger.id == 'location_change' }}"
        sequence:
          - service: homeassistant.update_entity
            target:
              entity_id: sensor.calendar_location_time
      - alias: "Time to work"
        conditions:
          - condition: template
            value_template: "{{ trigger.id == 'workdays_start' }}"
          - condition: state
            entity_id: binary_sensor.workday_sensor
            state: "on"
        sequence:
          - service: homeassistant.update_entity
            target:
              entity_id: sensor.miguel_eta_work
      - alias: "Time to home from work"
        conditions:
          - condition: template
            value_template: "{{ trigger.id == 'workdays_end' }}"
          - condition: state
            entity_id: binary_sensor.workday_sensor
            state: "on"
        sequence:
          - service: homeassistant.update_entity
            target:
              entity_id: sensor.miguel_eta_home
      - alias: "Periodic updates"
        conditions:
          - condition: template
            value_template: "{{ trigger.id == 'periodic' }}"
        sequence:
          - alias: "Check if travel time to work should be updated"
            if:
              - condition: time
                after: "08:00:00"
                before: "11:00:00"
              - condition: state
                entity_id: binary_sensor.workday_sensor
                state: "on"
              - condition: state
                entity_id: person.miguel
                state: "home"
              - alias: "Check home office"
                condition: not
                conditions:
                  - condition: or
                    conditions:
                      - condition: state
                        entity_id: sensor.bcwmc5cg4100cy0_nutzerbenachrichtigung
                        state: "AcceptsNotifications"
                      - condition: state
                        entity_id: sensor.bcwmc5cg4100cy0_nutzerbenachrichtigung
                        state: "NotPresent"
            then:
              - service: homeassistant.update_entity
                target:
                  entity_id: sensor.miguel_eta_work
          - alias: "Check if travel time from work to home should be updated"
            if:
              - condition: time
                after: "15:00:00"
                before: "20:00:00"
              - condition: state
                entity_id: binary_sensor.workday_sensor
                state: "on"
              - condition: state
                entity_id: person.miguel
                state: "work_miguel"
            then:
              - service: homeassistant.update_entity
                target:
                  entity_id: sensor.miguel_eta_home
