---
# Shower water sensor
alias: ShowerWater
id: 088d95b7-fe66-4f6f-b451-36f57089a574
description: "Setzt den Duschstatus anhand des Wassersensors"
trigger:
  - platform: state
    entity_id: binary_sensor.duschsensor_water_leak
condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: binary_sensor.duschsensor_water_leak
        state: "on"
      - condition: state
        entity_id: binary_sensor.duschsensor_water_leak
        state: "off"
action:
  - if:
      - condition: state
        entity_id: binary_sensor.duschsensor_water_leak
        state: "on"
    then:
      - service: input_boolean.turn_on
        entity_id: input_boolean.shower_active
    else:
      - service: input_boolean.turn_off
        entity_id: input_boolean.shower_active
mode: single
