---
# Wedding day
# sensor.anniversary_special_hochzeitstag
alias: weddingDay
id: 434eeb1e-ac51-4b60-a424-736b54d44c9b
description: "Hochzeitstag"
trigger:
  - platform: state
    entity_id: sensor.anniversary_special_hochzeitstag
condition:
  - condition: or
    conditions:
      - condition: template
        value_template: |-
          {{ states(trigger.entity_id) == 0 }}
      - condition: template
        value_template: |-
          {{ states(trigger.entity_id) >= 363 }}
action:
  - if:
      - condition: template
        value_template: |-
          {{ states(trigger.entity_id) == 0 }}
    then:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.herz
    else:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.herz
mode: single
