---
alias: LivetickerHandball
id: da7da451-5434-4399-b5bc-8d6e3a78782e
description: "Liveticker Handball"
trigger:
  - trigger: state
    entity_id:
      - sensor.sg_heuchelberg_live_events
      - sensor.tv_1895_flein_2_live_events
      - sensor.sg_heuchelberg_wja_live_events

condition:
  - condition: template
    value_template: >
      {% set from = trigger.from_state %}
      {% set to = trigger.to_state %}
      {% if from is none or to is none %}
        false
      {% else %}
        {{ to.attributes.total_events | int > from.attributes.total_events | int }}
      {% endif %}
action:
  - service: script.notify_engine
    data:
      title: |
        Liveticker
      value1: |
        {% set latest_event = trigger.to_state.attributes.events | sort(attribute='timestamp', reverse=true) | first %}
        {{ latest_event.message }} - {{ latest_event.score }} ({{ latest_event.time }})
      who: "home"
      tag_id: "information"
      group: "Sport"
mode: parallel
