---
# Scheduled vacuum cleaner run
description: "Scheduled vacuum cleaner run"
alias: "Scheduled vacuum cleaner run"
id: 146acdcd-843c-41d5-b727-b171a446a4d0
mode: single
trigger:
  - platform: state
    entity_id:
      - schedule.staubsaug_zeiten
    to: "on"
condition:
  - condition: state
    entity_id: input_boolean.automatic_cleaning
    state: "on"
action:
  - service: script.cleaning
    data: {}
