---
alias: SchlafzimmerButton
id: 94f7c73f-22dd-4b48-9ce2-d94971707ad1
description: "Schlafzimmerlicht per Button steuern"
mode: single
trigger:
  - platform: device
    domain: mqtt
    device_id: 5797af2e16357926c2be0ae3f95119c6
    type: action
    subtype: "on"
    discovery_id: 0x003c84fffe1d2a03 action_on
    id: "on"
  - platform: device
    domain: mqtt
    device_id: d5ea1ecd92f19d54b422d108948c3fd6
    type: action
    subtype: "on"
    discovery_id: 0x84b4dbfffe7126aa action_on
    id: "on_1"
  - platform: device
    domain: mqtt
    device_id: 5797af2e16357926c2be0ae3f95119c6
    type: action
    subtype: "off"
    discovery_id: 0x003c84fffe1d2a03 action_off
    id: "off"
  - platform: device
    domain: mqtt
    device_id: d5ea1ecd92f19d54b422d108948c3fd6
    type: action
    subtype: "off"
    discovery_id: 0x84b4dbfffe7126aa action_off
    id: "off_1"

condition: []
action:
  - if:
      - condition: template
        value_template: "{{  trigger.id == 'on' or trigger.id == 'on_1' }}"
    then:
      - service: light.turn_on
        data: {}
        target:
          entity_id: light.schlafzimmerlicht
    else:
      - service: light.turn_off
        data: {}
        target:
          entity_id: light.schlafzimmerlicht
