---
#  Zigbee Lichtschalter Milo
alias: "MiloLichtschalter"
id: 7999a5fd-f97d-4a9c-be35-39a400084e2c
description: "Schaltet das Licht an und aus"
mode: single
trigger:
  - device_id: 3d6fc3ce48f8001dd5e008a11f12e20e
    domain: zha
    type: remote_button_short_press
    subtype: turn_on
    trigger: device
    id: "on"
  - device_id: 3d6fc3ce48f8001dd5e008a11f12e20e
    domain: zha
    type: remote_button_short_press
    subtype: turn_off
    trigger: device
    id: "off"
condition: []
action:
  - if:
      - condition: template
        value_template: "{{  trigger.id == 'on' }}"
    then:
      - action: light.turn_on
        data: {}
        target:
          entity_id: light.esstischlicht
    else:
      - action: light.turn_off
        data: {}
        target:
          entity_id: light.esstischlicht
