DOMAIN = "handballnet"
CONF_TEAM_ID = "team_id"
CONF_LEAGUE_ID = "league_id"
CONF_UPDATE_INTERVAL = "update_interval"
DEFAULT_UPDATE_INTERVAL = 3600  
CONF_UPDATE_INTERVAL_LIVE = "update_interval_live"
DEFAULT_UPDATE_INTERVAL_LIVE = 15