---
# Automatisierung, wenn jemand im Bett erkannt wurde oder alle aufgestanden sind
alias: BedAutomation
id: 6bb1782f-56aa-4ebc-b5ab-64e9f185f93f
description: "Automatisierung, wenn jemand im Bett erkannt wurde oder alle aufgestanden sind"
mode: single
trigger:
  - platform: state
    entity_id: binary_sensor.bett_tracker
    to:
      - "on"
      - "off"
    for:
      minutes: 2
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.bett_tracker
            state: "on"
            alias: "Check if someone is in bed"
        sequence:
          - action: switch.turn_on
            target:
              entity_id: switch.echo_schlafzimmer_bitte_nicht_storen
          - action: light.turn_on
            target:
              entity_id: light.bett
            alias: "Turn on bed light"
          - if:
              - condition: state
                state:
                  - above_horizon
                entity_id: sun.sun
            then:
              - action: cover.close_cover
                target:
                  entity_id: cover.rollladen_schlafzimmer
          - if:
              - condition: state
                entity_id: binary_sensor.schlafenszeit
                state: "on"
            then:
              - action: input_boolean.turn_on
                target:
                  entity_id: input_boolean.night_mode
            alias: "Enable night mode if bedtime"

      - conditions:
          - condition: state
            entity_id: binary_sensor.bett_tracker
            state: "off"
            alias: "Check if everyone is up"
        sequence:
          - action: switch.turn_off
            target:
              entity_id: switch.echo_schlafzimmer_bitte_nicht_storen
          - action: switch.turn_off
            target:
              entity_id: switch.babyphone
          - action: light.turn_off
            target:
              entity_id: light.bett
            alias: "Turn off bed light"
          - if:
              - condition: state
                entity_id: binary_sensor.sonne_im_wohnzimmer
                state: "on"
            then:
              - action: cover.set_cover_position
                target:
                  entity_id: cover.rollladen_schlafzimmer
                data:
                  position: 25
            alias: "Lower bedroom cover if sunny"
          - if:
              - condition: state
                entity_id: binary_sensor.schlafenszeit
                state: "on"
            then:
              - action: input_boolean.turn_off
                target:
                  entity_id: input_boolean.night_mode
            alias: "Disable night mode if bedtime"
