---
# Display birthdays
alias: Show birthdays on clock
id: 18139b1d-4666-4261-b024-e737cf1e9159
description: "Show birthdays on clock"
trigger:
  - platform: time
    at: "00:00:00"
condition: []
action:
  - variables:
      triggered_entity: >-
        {{ states | selectattr('entity_id', 'match',
        'sensor.anniversary_birthday_') | selectattr('state', 'eq', '0') | map(attribute='entity_id') | list
        | first }}
  - if:
      - condition: template
        value_template: "{{ triggered_entity != '' }}"
    then:
      - action: script.awtrix3customapp
        data:
          app_id: birthday
          text: "{{ state_attr(triggered_entity, 'friendly_name') }}"
          icon: "102"
    else:
      - action: script.awtrix3delapp
        data:
          app_id: birthday
mode: single
