---
# Festnetzbenachrichtigung
alias: UhrFestnetz
id: 9369a9dc-88fb-4ee8-a724-94559678db81
description: "Uhr Festnetz"
trigger:
  - platform: state
    entity_id: sensor.fritz_box_7590_ax_anrufmonitor_telefonbuch
condition: []
action:
  - variables:
      from: >-
        {{ trigger.from_state.attributes.from_name }} - {{ trigger.from_state.attributes.from}}
  - if:
      - condition: template
        value_template: "{{  trigger.to_state.state == 'ringing' }}"
    then:
      - action: script.awtrix3customapp
        data:
          app_id: phone
          text: "{{ from }}"
          icon: "1232"
          duration: 30
  # - delay:
  #     seconds: 1
  # - action: script.awtrix3switch2app
  #   data:
  #     app_id: phone
  - if:
      - condition: or
        conditions:
          - condition: and
            alias: "Verpasst"
            conditions:
              - condition: template
                value_template: "{{ trigger.to_state.state == 'idle' }}"
              - condition: template
                value_template: "{{ trigger.from_state.state == 'ringing' }}"
          - condition: and
            alias: "AB Weiterleitung"
            conditions:
              - condition: template
                value_template: "{{  trigger.to_state.state == 'talking' }}"
              - condition: template
                value_template: "{{ trigger.to_state.attributes.device == '40' }}"
    then:
      - action: script.awtrix3customapp
        data:
          app_id: phone
          text: "{{ from }}"
          icon: "21482"
          duration: 30
    else:
      - action: script.awtrix3delapp
        data:
          app_id: phone
mode: single
