---
# Festnetzbenachrichtigung
alias: UhrFestnetz
id: 9369a9dc-88fb-4ee8-a724-94559678db81
description: "Uhr Festnetz"
trigger:
  - platform: state
    entity_id: sensor.fritz_box_7590_ax_anrufmonitor_telefonbuch
condition: []
action:
  - variables:
      from_state: >-
        {% if trigger.from_state.attributes.from_name %}
          {{ trigger.from_state.attributes.from_name }}
        {% else %}
          {{ trigger.from_state.attributes.from }}
        {% endif %}
      to_state: >-
        {% if trigger.to_state.attributes.from_name %}
          {{ trigger.to_state.attributes.from_name }}
        {% else %}
          {{ trigger.to_state.attributes.from }}
        {% endif %}
  - if:
      - condition: template
        value_template: "{{  trigger.to_state.state == 'ringing' }}"
    then:
      - action: script.awtrix3notif
        data:
          text: "{{ to_state }}"
          icon: "1232"
          repeat: 2
          rainbow: true
          duration: 15
  - if:
      - condition: or
        conditions:
          - condition: and
            alias: "Verpasst"
            conditions:
              - condition: template
                value_template: "{{ trigger.to_state.state == 'idle' }}"
              - condition: template
                value_template: "{{ trigger.from_state.state == 'ringing' }}"
          - condition: and
            alias: "AB Weiterleitung"
            conditions:
              - condition: template
                value_template: "{{  trigger.to_state.state == 'talking' }}"
              - condition: template
                value_template: "{{ trigger.to_state.attributes.device == '40' }}"
    then:
      - action: script.awtrix3customapp
        data:
          app_id: phone
          text: "{{ from_state }}"
          icon: "21482"
          duration: 15
    else:
      - action: script.awtrix3delapp
        data:
          app_id: phone
mode: single
