---
# Display dwd warning
alias: Show dwd warning on clock
id: 6ce30133-5f41-456c-a80f-111fbe92bd0c
description: "Show dwd warning on clock"
trigger:
  - platform: state
    entity_id: sensor.home_aktuelle_warnstufe
condition: []
action:
  - variables:
      warn_count: "{{ state_attr('sensor.home_aktuelle_warnstufe', 'warning_count') | int(0) }}"
  - repeat:
      for_each: "{{ range(1, warn_count + 1) | list }}"
      sequence:
        - service: script.awtrix3customapp
          data:
            app_id: "dwd_{{ repeat.item }}"
            text: "{{ state_attr('sensor.home_aktuelle_warnstufe', 'warning_' ~ repeat.item ~ '_name') }}"
            icon: "6874"
  - variables:
      max_possible: 3
  - repeat:
      for_each: "{{ range(warn_count + 1, max_possible + 1) | list }}"
      sequence:
        - service: script.awtrix3delapp
          data:
            app_id: "dwd_{{ repeat.item }}"
mode: single
