---
# Show daily hot beverages
alias: Show daily hot beverages
id: c8718743-1084-41e6-a047-3483fe692c8b
description: "Show daily hot beverages"
trigger:
  - platform: state
    entity_id: input_number.heissgetranke_zahler
condition: []
action:
  - if:
      - condition: state
        entity_id: input_number.heissgetranke_zahler
        state: "0"
    then:
      - action: script.awtrix3delapp
        data:
          app_id: coffee
    else:
      - action: script.awtrix3customapp
        data:
          app_id: coffee
          text: "{{ states('input_number.heissgetranke_zahler') | int }}"
          icon: "14060"
mode: single
