---
# sensor.wohnungstemperatur
alias: Show humidity on clock
id: e90f58ed-9d21-499f-aa84-81a9e2523643
description: " Show humidity on clock"
trigger:
  - platform: state
    entity_id: sensor.wohnungsfeuchtigkeit
condition: []
action:
  - action: script.awtrix3customapp
    data:
      app_id: humidity
      text: "{{ states('sensor.wohnungsfeuchtigkeit') | float(0) | round(2) }}  {{ state_attr('sensor.wohnungsfeuchtigkeit', 'unit_of_measurement') }}"
      icon: "39041"
mode: single
