---
# sensor.anniversary_special_b_mini
alias: Show mini countdown on clock
id: 5ce560a2-c147-40f0-b02f-46ba328c5b84
description: "Show mini countdown on clock"
triggers:
  - trigger: time
    at: "00:01:00"
  - trigger: state
    entity_id: input_boolean.holiday_mode
  - trigger: homeassistant
    event: start
conditions: []
actions:
  - variables:
      mini: sensor.anniversary_special_b_mini
  - action: script.awtrix_app
    data:
      app_id: mini
      show: >-
        {{ is_state('group.parents', 'home')
          and is_state('input_boolean.holiday_mode', 'off')
          and states(mini) | float(-1) >= 0 }}
      text: >-
        {{ states(mini) }} {{ state_attr(mini, 'unit_of_measurement') }}
      icon: "365"
      lifetime_ms: 90000000
mode: single
