---
#
alias: Show paper waste on clock
id: 4aa8ddd2-7dc5-4b0f-98a0-3979e5496ed1
description: "Show paper waste on clock"
trigger:
  - platform: state
    entity_id: sensor.papier
condition: []
action:
  - if:
      - condition: template
        value_template: "{{ state_attr('sensor.papier', 'daysTo') <= '1' }}"
    then:
      - action: script.awtrix3customapp
        data:
          app_id: paper_waste
          text: "{{ state_attr('sensor.papier', 'friendly_name') }}"
          icon: "57286"
    else:
      - action: script.awtrix3delapp
        data:
          app_id: paper_waste
mode: single
