---
# Person state
alias: "Awtrix - Person State Display"
id: 5b390c50-4a81-42b7-b628-1cd4a3acd55f
description: "Combined automation to show family status on Awtrix clock"
mode: restart
triggers:
  - trigger: state
    entity_id:
      - person.milo_carlos
      - person.miguel
      - person.finn_manuel
      - person.silke
      - person.maja
  - trigger: state
    entity_id: input_boolean.holiday_mode
    to: "off"
conditions:
  - condition: state
    entity_id: input_boolean.holiday_mode
    state: "off"
actions:
  - repeat:
      for_each:
        - entity_id: person.milo_carlos
          app_name: milo
          icon_id: "41425"
        - entity_id: person.miguel
          app_name: miguel
          icon_id: "28759"
        - entity_id: person.finn_manuel
          app_name: finn
          icon_id: "48342"
        - entity_id: person.silke
          app_name: silke
          icon_id: "19702"
        - entity_id: person.maja
          app_name: maja
          icon_id: "76"
      sequence:
        - action: script.awtrix_app
          data:
            app_id: "{{ repeat.item.app_name }}"
            show: >-
              {{ states(repeat.item.entity_id)
                not in ['home', 'unknown', 'unavailable'] }}
            text: "{{ state_translated(repeat.item.entity_id) }}"
            icon: "{{ repeat.item.icon_id }}"
