---
# 14397
alias: Show special days on clock
id: 10af4661-0fb0-4b0e-9b0d-e5ae7d251d93
description: "Show special days on clock"
trigger:
  - trigger: time
    at: "00:01:00"
  - trigger: time
    at: "11:11:00"
    id: "fasnacht"
condition: []
action:
  - variables:
      special_day: "{{ states('sensor.special_day') }}"
      icon: "{{ states('sensor.special_day_icon_awtrix') }}"
  - if:
      - condition: template
        value_template: "{{ special_day != 'none' }}"
    then:
      - action: script.awtrix3customapp
        data:
          app_id: special_day
          text: "{{ special_day }}"
          icon: "{{ icon }}"
    else:
      - action: script.awtrix3delapp
        data:
          app_id: special_day
  - if:
      - condition: template
        value_template: "{{ special_day == 'Fasnachtszeit'}}"
    then:
      - action: script.spotify_audio
        data:
          volume: 0.6
          type: song
          media_id: >-
            https://open.spotify.com/intl-de/track/1PnokXw6l4LGNaxl68ESRJ
          source: Echo_Show
mode: single
