---
# Display state silke
alias: Show state of silke
id: 9503b5e7-7f22-4687-afd2-c9aed8be4696
description: "Show silkes state on clock"
trigger:
  - platform: state
    entity_id: person.silke
condition:
  - condition: state
    entity_id: input_boolean.holiday_mode
    state: "off"
action:
  - if:
      - condition: state
        entity_id: person.silke
        state: "home"
    then:
      - action: script.awtrix3delapp
        data:
          app_id: silke
    else:
      - action: script.awtrix3customapp
        data:
          app_id: silke
          text: "{{ states('person.silke') }}"
          icon: "19702"
mode: single
