---
# Display state milo
alias: Show state of milo
id: 5c77626e-e4bc-4133-962d-3c8b1ce0e900
description: "Show finn state on clock"
trigger:
  - platform: state
    entity_id: person.finn_manuel
condition:
  - condition: state
    entity_id: input_boolean.holiday_mode
    state: "off"
action:
  - if:
      - condition: state
        entity_id: person.finn_manuel
        state: "home"
    then:
      - action: script.awtrix3delapp
        data:
          app_id: finn
    else:
      - action: script.awtrix3customapp
        data:
          app_id: finn
          text: "{{ states('person.finn_manuel') }}"
          icon: "48342"
mode: single
