---
# Display state milo
alias: Show state of milo
id: de7d8756-e929-4001-ade4-1c02b9a2c5c6
description: "Show milos state on clock"
trigger:
  - platform: state
    entity_id: person.milo_carlos
condition:
  - condition: state
    entity_id: input_boolean.holiday_mode
    state: "off"
action:
  - if:
      - condition: state
        entity_id: person.milo_carlos
        state: "home"
    then:
      - action: script.awtrix3delapp
        data:
          app_id: milo
    else:
      - action: script.awtrix3customapp
        data:
          app_id: milo
          text: "{{ states('person.milo_carlos') }}"
          icon: "48342"
mode: single
