---
alias: Show timer on clock
id: 2c96d793-ea37-49cb-89c2-972a4518789b
trigger:
  - platform: state
    entity_id:
      - sensor.echo_buro_nachster_timer
      - sensor.echo_show_nachster_timer
      - sensor.milos_dot_nachster_timer
  - platform: time_pattern
    seconds: "/5"

action:
  - repeat:
      for_each:
        - entity_id: sensor.echo_buro_nachster_timer
          text: Büro
          id: office
          icon: 8135
        - entity_id: sensor.echo_show_nachster_timer
          id: kitchen
          text: Küche
          icon: 57796
        - entity_id: sensor.milos_dot_nachster_timer
          id: living
          text: Wohnzimmer
          icon: 63810
      sequence:
        - variables:
            raw_state: "{{ states(repeat.item.entity_id) }}"
            is_valid: "{{ raw_state not in ['unavailable', 'unknown', 'none', ''] }}"
            timer_active: >-
              {% if is_valid %}
                {{ (raw_state | as_datetime) > now() }}
              {% else %}
                false
              {% endif %}

        - if:
            - condition: template
              value_template: "{{ timer_active }}"
          then:
            - variables:
                timer_end: "{{ raw_state | as_datetime }}"
                start: "{{ states[repeat.item.entity_id].last_changed | as_datetime }}"
                total: "{{ (timer_end - start).total_seconds() }}"
                elapsed: "{{ (now() - start).total_seconds() }}"
                progress_bar: >-
                  {% if total > 0 %}
                    {{ ([0, (elapsed / total * 100) | round(2), 100] | sort)[1] }}
                  {% else %}
                    0
                  {% endif %}
            - action: script.awtrix3customapp
              data:
                app_id: "timer_{{ repeat.item.id }}"
                text: "{{ repeat.item.text }}"
                icon: "{{ repeat.item.icon }}"
                progress: "{{ progress_bar }}"
          else:
            - action: script.awtrix3delapp
              data:
                app_id: "timer_{{ repeat.item.id }}"
mode: restart
