---
#
alias: Show waste on clock
id: 33ea773e-67d2-4f5c-97ba-778d098b0ade
description: "Show waste on clock"
trigger:
  - platform: state
    entity_id: sensor.restmull
  - platform: state
    entity_id: sensor.papier
  - platform: state
    entity_id: sensor.bio
  - platform: state
    entity_id: sensor.schadstoffe
condition: []
action:
  - if:
      - condition: template
        value_template: "{{ trigger.to_state.attributes.daysTo | int <= 1 }}"
    then:
      - action: script.awtrix3customapp
        data:
          app_id: "waste_{{ trigger.from_state.friendly_name }}"
          text: "{{ trigger.to_state.state }}"
          icon: "57283"
    else:
      - action: script.awtrix3delapp
        data:
          app_id: "waste_{{ trigger.from_state.friendly_name }}"
mode: parallel
