---
alias: Weather indicator TV
id: 54e10e2c-91a5-43cd-a7d2-d0087effef06
trigger:
  - platform: state
    entity_id:
      - weather.home
condition:
  - alias: Check if TV is turned on
    condition: state
    entity_id: media_player.fernseher_im_wohnzimmer
    state: "playing"
action:
  - service: notify.tvoverlaynotifyfixed
    data:
      data:
        id: fixed_weather
        icon: >-
          {% set weather_icons = {
            'sunny': 'mdi:weather-sunny',
            'clear-night': 'mdi:weather-night',
            'rainy': 'mdi:weather-rainy',
            'snowy': 'mdi:weather-snowy',
            'snowy-rainy': 'mdi:weather-snowy-rainy',
            'fog': 'mdi:weather-fog',
            'sleet': 'mdi:weather-partly-snowy-rainy',
            'wind': 'mdi:weather-windy',
            'cloudy': 'mdi:weather-cloudy',
            'partlycloudy': 'mdi:weather-partly-cloudy',
            'partlycloudy-night': 'mdi:weather-night-partly-cloudy',
            'hail': 'mdi:weather-hail',
            'lightning': 'mdi:weather-lightning',
            'thunderstorm': 'mdi:weather-lightning-rainy'
          } %}
          {{ weather_icons.get(states('weather.home'), 'mdi:weather-cloudy') }}
        expiration: 12h
        shape: circle
      message: "{{ state_attr('weather.home', 'temperature')  | round }}°"
mode: single
