---
# Reset medi booleans, that the notification can be send
alias: MedisResetBool
id: b67001f4-cf8f-414d-a1bb-84fe46b2b37b
description: "Medis reset"
trigger:
  - platform: time
    at: "00:01:00"
    id: "daily"
  - trigger: time
    at:
      entity_id: input_datetime.medis_reminder_time_morning
      offset: "-01:00:00"
    id: "morgens"
  - trigger: time
    at:
      entity_id: input_datetime.medis_reminder_time_evening
      offset: "-01:00:00"
    id: "mittags"
  - trigger: time
    at:
      entity_id: input_datetime.medis_reminder_time_night
      offset: "-01:00:00"
    id: "abends"
action:
  - if:
      - alias: "check if it is the daily Trigger"
        condition: template
        value_template: "{{  trigger.id == 'daily' }}"
    then:
      - action: input_boolean.turn_off
        target:
          label_id: medisdaily
      - variables:
          heuschnupfen: >
            {%- for medi in label_entities('MedisDaily') | list if states(medi) in ('on','off') -%}
              {%- if "heuschnupfen" in medi -%}
                {{ medi }}
              {%- endif -%}
            {%- endfor -%}
      - choose:
          - conditions: "{{ heuschnupfen != '' }}"
            sequence:
              - repeat:
                  for_each: "{{ heuschnupfen.split(' ') }}"
                  sequence:
                    - variables:
                        pollen_typ: "{{ repeat.item.split('_')[4] }}"
                        pollen_sensor: "sensor.pollenflug_{{ pollen_typ }}_112"
                    - condition: template
                      value_template: >
                        {{ states(repeat.item) != 'on' and states(pollen_sensor) | float == 0 }}
                    - action: input_boolean.turn_on
                      target:
                        entity_id: "{{ repeat.item }}"
        alias: "Heuschnupfen anschalten, wenn gerade keine Pollen unterwegs sind"
      - condition: time
        weekday:
          - sun
      - action: input_boolean.turn_off
        target:
          label_id: medisweekly
    else:
      - action: input_boolean.turn_off
        target:
          label_id:
            - medishourly
            - "{{ trigger.id }}"
