"""Protocols for game service dependencies — avoids circular imports (#465)."""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class MediaPlayerProtocol(Protocol):
    """Interface that GameState expects from a media-player service."""

    def set_analytics(self, analytics: Any) -> None: ...
    def is_available(self) -> bool: ...
    async def verify_responsive(self) -> tuple[bool, str]: ...
    async def play_song(self, song: dict[str, Any]) -> bool: ...
    async def wait_for_metadata_update(self, uri: str) -> dict[str, Any]: ...
    async def stop(self) -> bool: ...
    async def play(self) -> bool: ...
    def get_volume(self) -> float: ...
    async def set_volume(self, level: float) -> bool: ...


@runtime_checkable
class PartyLightsProtocol(Protocol):
    """Interface that GameState expects from a party-lights service."""

    async def start(self, entity_ids: list[str], intensity: str = "medium") -> None: ...
    async def set_phase(self, phase: Any) -> None: ...
    async def flash(self, color_name: str) -> None: ...
    async def celebrate(self) -> None: ...
    async def stop(self) -> None: ...
