---
# climate auto off timer
alias: heatingAutoOffTimer
id: 2f8c3e90-2cca-4eb7-b3ab-de6fe092222b
description: ""
trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.heating_auto_off
  - platform: event
    event_type: timer.cancelled
    event_data:
      entity_id: timer.heating_auto_off
condition: []
action:
  - service: climate.turn_off
    target:
      entity_id: climate.room_climate_wohnzimmer
mode: single
