---
alias: sunInRoom
id: 52bb62b0-9e87-4a6f-bbe1-e4213c60f4ea
description: ""
trigger:
  - platform: state
    entity_id: binary_sensor.sonne_im_wohnzimmer
    to: "on"
    alias: Sun hits living room
condition:
  - condition: state
    entity_id: input_boolean.sonnen_schutz_aktiv
    state: "on"
  - alias: "Check outside temperature"
    condition: numeric_state
    entity_id: sensor.temperatur
    above: "22"
action:
  - action: cover.set_cover_position
    target:
      entity_id: cover.rolladen_kinderzimmer
    data:
      position: 25
  - if:
      - alias: "Check if someone sleeps"
        condition: state
        entity_id: binary_sensor.bett_tracker
        state: "off"
    then:
      - action: cover.set_cover_position
        target:
          entity_id: cover.rollladen_schlafzimmer
        data:
          position: 25
  - action: cover.set_cover_position
    target:
      entity_id: cover.wohnzimmerrolladen
    data:
      position: 25
mode: single
