---
# Dog gone trigger
alias: MajaGassi
id: dee4478e-a5a0-499f-8072-65b249e0f58c
description: "Lässt den Staubsaugroboter laufen, wenn wir mit Maja draußen sind"
trigger:
  - device_id: aed74422c2bf9bba083e5bab68216278
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: turn_on
action:
  - service: script.gassi
    data: {}

mode: single
