---
# Shower automation
# binary_sensor.dusche
alias: Shower
id: 2e10ac5d-5d52-4006-9b95-b46e4d241b99
description: "Shower automation"
trigger:
  - platform: state
    entity_id: binary_sensor.dusche
    to: "on"
condition: []
action:
  - service: script.spotify_audio
    data:
      volume: 0.6
      type: playlist
      media_id: >-
        https://open.spotify.com/playlist/5r4YRJTzgAObYU4pXbWW9a?si=80e65565a3b24adb&pt=5c44bf58d4ec568bfccbf89cb14e8b3c
      source: Echo_Gross
mode: single
