---
#
sensor:
  template: setup
  variables:
    unit: "%"
  type: custom:button-card
  show_label: true
  custom_fields:
    eenheid: '[[[ return "&nbsp;" + variables.unit ]]]'
  styles:
    grid:
      - grid-template-areas: '"l eenheid" "n n"'
      - grid-template-columns: min-content min-content
    label:
      - font-size: 27px
      - color: var(--contrast20)
    card:
      - height: 80px
      - border-radius: 24px
      - padding: 0px 0 6px 16px
      - box-sizing: border-box
      - background: var(--contrast2)
      - box-shadow: none
    name:
      - justify-self: start
      - font-size: 12px
      - color: var(--contrast20)
      - margin-top: "-30px"
    custom_fields:
      eenheid:
        - font-size: 12px
        - color: var(--contrast9)
        - padding-left: 2px
  tap_action:
    action: more-info
