---
# BT Proxy
substitutions:
  name: kueche-proxy
  friendly_name: Küche Proxy
packages:
  esphome.bluetooth-proxy: github://esphome/firmware/bluetooth-proxy/m5stack-atom-lite.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret kueche_proxy_encryption

web_server:
  port: 80

improv_serial:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret home_domain
  manual_ip:
    static_ip: 192.168.0.78
    gateway: !secret wifi_gateway
    subnet: !secret wifi_subnet
  ap:
    password: !secret wifi_fallback_password
