---
# BT Proxy
substitutions:
  name: atom-bluetooth-proxy-a05be4
  friendly_name: Büro Proxy
packages:
  esphome.bluetooth-proxy: github://esphome/firmware/bluetooth-proxy/m5stack-atom-lite.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret buero_proxy_encryption

improv_serial:

web_server:
  port: 80

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.0.7
    gateway: !secret wifi_gateway
    subnet: !secret wifi_subnet
